package catalog

import (
	"fmt"
	"sort"
	"strings"
)

// Rendering for cmd/gen-catalog-docs. Kept in this package so the
// regenerate-and-compare conformance test and the generator share one
// implementation.

const generatedMarker = "<!-- Code generated by gen-catalog-docs from catalog/; DO NOT EDIT. -->"

// GeneratedDocs is the single definition of which files gen-catalog-docs
// produces: repo-root-relative path -> rendered content. The generator
// writes them; the conformance test regenerates and compares.
func GeneratedDocs(entries []Entry) map[string]string {
	return map[string]string{
		"docs/reference/DIAGNOSTICS.md": RenderDiagnosticsDoc(entries),
		"docs/STATUS.md":                RenderStatusDoc(entries),
	}
}

// RenderDiagnosticsDoc renders docs/reference/DIAGNOSTICS.md: the full rule
// table keyed by code slug.
func RenderDiagnosticsDoc(entries []Entry) string {
	var b strings.Builder
	b.WriteString(generatedMarker + "\n\n")
	b.WriteString("# Diagnostic Rules\n\n")
	b.WriteString("One row per diagnostic code. The normative definition of each rule —\n")
	b.WriteString("expected behavior, executable examples, decision history — is its\n")
	b.WriteString("catalog entry under `catalog/diagnostics/`. Severity can be overridden\n")
	b.WriteString("per rule via `ssl.diagnostics.rules`; suppressible rules honor\n")
	b.WriteString("`@ssl-disable` comments (see docs/configuration/CONFIGURATION.md §5).\n\n")
	b.WriteString("| Code | Title | Default severity | Authority | Status | Entry |\n")
	b.WriteString("|------|-------|------------------|-----------|--------|-------|\n")

	sorted := make([]Entry, 0, len(entries))
	for _, e := range entries {
		if e.Kind == KindDiagnostic {
			sorted = append(sorted, e)
		}
	}
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })

	for _, e := range sorted {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | [%s](../../catalog/diagnostics/%s.md) |\n",
			e.Slug(), e.Title, e.DefaultSeverity, e.Authority, e.Status, e.ID, e.Slug())
	}
	return b.String()
}

// RenderStatusDoc renders docs/STATUS.md: a compact dashboard generated from
// the catalog, replacing the previously hand-maintained (and stale) file.
func RenderStatusDoc(entries []Entry) string {
	var b strings.Builder
	b.WriteString(generatedMarker + "\n\n")
	b.WriteString("# Implementation Status\n\n")
	b.WriteString("Generated from the behavior catalog (`catalog/`), the normative\n")
	b.WriteString("source of truth. Status meanings: `active` = specified and enforced\n")
	b.WriteString("by executable spec; `draft` = implemented, entry awaiting review;\n")
	b.WriteString("`planned` = specified, not implemented; `removed` = deliberately\n")
	b.WriteString("dropped (entry retains the history).\n\n")

	kinds := []struct{ kind, title string }{
		{KindFeature, "Features"},
		{KindFormatter, "Formatter behaviors"},
	}
	for _, k := range kinds {
		b.WriteString("## " + k.title + "\n\n")
		b.WriteString("| Entry | Title | Status |\n|-------|-------|--------|\n")
		for _, e := range sortedByID(entries, k.kind) {
			dir := kindDirs[e.Kind].dir
			fmt.Fprintf(&b, "| [%s](../catalog/%s/%s.md) | %s | %s |\n", e.ID, dir, e.Slug(), e.Title, e.Status)
		}
		b.WriteString("\n")
	}

	counts := map[string]int{}
	total := 0
	for _, e := range entries {
		if e.Kind == KindDiagnostic {
			counts[e.Status]++
			total++
		}
	}
	b.WriteString("## Diagnostics\n\n")
	fmt.Fprintf(&b, "%d rules cataloged: %d active, %d draft, %d planned, %d removed.\n",
		total, counts[StatusActive], counts[StatusDraft], counts[StatusPlanned], counts[StatusRemoved])
	b.WriteString("Full table: [docs/reference/DIAGNOSTICS.md](reference/DIAGNOSTICS.md).\n")
	return b.String()
}

func sortedByID(entries []Entry, kind string) []Entry {
	var out []Entry
	for _, e := range entries {
		if e.Kind == kind {
			out = append(out, e)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}
