// Command gen-inventory regenerates the SSL element inventory Go files from
// the canonical ssl-element-reference.json snapshot.
//
// It is invoked via `go generate ./internal/constants/...`. The vendored
// JSON lives at internal/constants/data/ssl-element-reference.json (refresh
// procedure documented in that directory's README.md). Output files have
// names matching internal/constants/generated_*.go and start with the
// standard "Code generated by gen-inventory; DO NOT EDIT." marker.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// JSON shape — see ssl-style-guide/tools/generate_element_reference.py for
// the producer side.

type tableRow map[string]string

type referenceEntry struct {
	Title        string                 `json:"title"`
	Summary      string                 `json:"summary"`
	Syntax       string                 `json:"syntax,omitempty"`
	TypeBehavior []tableRow             `json:"type_behavior,omitempty"`
	RuntimeType  string                 `json:"runtime_type,omitempty"`
	Operators    []tableRow             `json:"operators,omitempty"`
	Members      []tableRow             `json:"members,omitempty"`
	Constructors []constructorReference `json:"constructors,omitempty"`
	Properties   []tableRow             `json:"properties,omitempty"`
	Methods      []tableRow             `json:"methods,omitempty"`
	BaseClass    string                 `json:"base_class,omitempty"`
	Signature    string                 `json:"signature,omitempty"`
	Returns      *returnsReference      `json:"returns,omitempty"`
	Parameters   []tableRow             `json:"parameters,omitempty"`
}

type constructorReference struct {
	Signature   string     `json:"signature"`
	Description string     `json:"description,omitempty"`
	Parameters  []tableRow `json:"parameters,omitempty"`
}

type returnsReference struct {
	Type        string `json:"type"`
	Description string `json:"description,omitempty"`
}

type referenceFile struct {
	Version      string                    `json:"version"`
	Source       string                    `json:"source"`
	Totals       map[string]int            `json:"totals"`
	Keywords     map[string]referenceEntry `json:"keywords"`
	Operators    map[string]referenceEntry `json:"operators"`
	Literals     map[string]referenceEntry `json:"literals"`
	Types        map[string]referenceEntry `json:"types"`
	Classes      map[string]referenceEntry `json:"classes"`
	SpecialForms map[string]referenceEntry `json:"special_forms"`
	Functions    map[string]referenceEntry `json:"functions"`
}

func main() {
	var (
		inputPath string
		outputDir string
	)
	flag.StringVar(&inputPath, "in", "internal/constants/data/ssl-element-reference.json",
		"Path to the canonical reference JSON.")
	flag.StringVar(&outputDir, "out", "internal/constants",
		"Directory to write generated_*.go files to.")
	flag.Parse()

	abs, err := filepath.Abs(inputPath)
	if err != nil {
		fail("resolving input path: %v", err)
	}
	raw, err := os.ReadFile(abs)
	if err != nil {
		fail("reading %s: %v", abs, err)
	}

	var ref referenceFile
	if err := json.Unmarshal(raw, &ref); err != nil {
		fail("parsing %s: %v", abs, err)
	}

	writers := []struct {
		name string
		fn   func(*referenceFile) []byte
	}{
		{"generated_inventory.go", emitInventory},
		{"generated_keywords.go", emitKeywords},
		{"generated_operators.go", emitOperators},
		{"generated_literals.go", emitLiterals},
		{"generated_types.go", emitTypes},
		{"generated_classes.go", emitClasses},
		{"generated_special_forms.go", emitSpecialForms},
		{"generated_functions.go", emitFunctions},
	}

	for _, w := range writers {
		body := w.fn(&ref)
		formatted, err := format.Source(body)
		if err != nil {
			fail("gofmt %s: %v\n----- raw output -----\n%s", w.name, err, body)
		}
		dest := filepath.Join(outputDir, w.name)
		if err := os.WriteFile(dest, formatted, 0o644); err != nil {
			fail("writing %s: %v", dest, err)
		}
		fmt.Printf("Wrote %s (%d bytes)\n", dest, len(formatted))
	}
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}

// ---------- helpers ----------

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// canonicalSorted returns map keys sorted by the case-insensitive form of
// each key. Used for keyword/class buckets where the JSON uses uppercase or
// PascalCase keys but we want deterministic stable output.
func canonicalSorted[V any](m map[string]V) []string {
	keys := sortedKeys(m)
	sort.SliceStable(keys, func(i, j int) bool {
		return strings.ToLower(keys[i]) < strings.ToLower(keys[j])
	})
	return keys
}

// quote escapes a Go string literal.
func quote(s string) string {
	return strconvQuote(s)
}

func strconvQuote(s string) string {
	// Use json.Marshal for safe escaping (handles all unicode + control chars).
	b, err := json.Marshal(s)
	if err != nil {
		return `""`
	}
	return string(b)
}

// row helpers — pull a field from a tableRow by trying several column names.
func cell(row tableRow, names ...string) string {
	for _, n := range names {
		if v, ok := row[n]; ok && v != "" {
			return v
		}
	}
	return ""
}

func writeHeader(buf *bytes.Buffer, doc string) {
	buf.WriteString("// Code generated by cmd/gen-inventory; DO NOT EDIT.\n")
	buf.WriteString("// Source: internal/constants/data/ssl-element-reference.json\n")
	buf.WriteString("\n")
	buf.WriteString("package constants\n\n")
	if doc != "" {
		buf.WriteString("// ")
		buf.WriteString(doc)
		buf.WriteString("\n\n")
	}
}

// ---------- emitters ----------

func emitInventory(ref *referenceFile) []byte {
	var buf bytes.Buffer
	writeHeader(&buf, "Inventory totals derived from the published SSL element reference.")

	buf.WriteString("// InventoryTotals reports element counts by category.\n")
	buf.WriteString("var InventoryTotals = struct {\n")
	buf.WriteString("\tKeywords     int\n")
	buf.WriteString("\tOperators    int\n")
	buf.WriteString("\tLiterals     int\n")
	buf.WriteString("\tTypes        int\n")
	buf.WriteString("\tClasses      int\n")
	buf.WriteString("\tSpecialForms int\n")
	buf.WriteString("\tFunctions    int\n")
	buf.WriteString("\tAll          int\n")
	buf.WriteString("}{\n")
	fmt.Fprintf(&buf, "\tKeywords:     %d,\n", len(ref.Keywords))
	fmt.Fprintf(&buf, "\tOperators:    %d,\n", len(ref.Operators))
	fmt.Fprintf(&buf, "\tLiterals:     %d,\n", len(ref.Literals))
	fmt.Fprintf(&buf, "\tTypes:        %d,\n", len(ref.Types))
	fmt.Fprintf(&buf, "\tClasses:      %d,\n", len(ref.Classes))
	fmt.Fprintf(&buf, "\tSpecialForms: %d,\n", len(ref.SpecialForms))
	fmt.Fprintf(&buf, "\tFunctions:    %d,\n", len(ref.Functions))
	all := len(ref.Keywords) + len(ref.Operators) + len(ref.Literals) +
		len(ref.Types) + len(ref.Classes) + len(ref.SpecialForms) +
		len(ref.Functions)
	fmt.Fprintf(&buf, "\tAll:          %d,\n", all)
	buf.WriteString("}\n")
	return buf.Bytes()
}

func emitKeywords(ref *referenceFile) []byte {
	var buf bytes.Buffer
	writeHeader(&buf, "Generated keyword inventory and details (38 keywords).")

	buf.WriteString("// GeneratedKeywords lists every published SSL keyword in canonical (uppercase) form.\n")
	buf.WriteString("var GeneratedKeywords = []string{\n")
	for _, k := range canonicalSorted(ref.Keywords) {
		fmt.Fprintf(&buf, "\t%s,\n", quote(k))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("// GeneratedKeywordDetails maps each keyword (uppercase, no leading colon) to its published title, summary, and syntax block.\n")
	buf.WriteString("var GeneratedKeywordDetails = map[string]KeywordDetails{\n")
	for _, k := range canonicalSorted(ref.Keywords) {
		entry := ref.Keywords[k]
		fmt.Fprintf(&buf, "\t%s: {\n", quote(k))
		fmt.Fprintf(&buf, "\t\tTitle:   %s,\n", quote(entry.Title))
		fmt.Fprintf(&buf, "\t\tSummary: %s,\n", quote(entry.Summary))
		if entry.Syntax != "" {
			fmt.Fprintf(&buf, "\t\tSyntax:  %s,\n", quote(entry.Syntax))
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")
	return buf.Bytes()
}

func emitOperators(ref *referenceFile) []byte {
	// Symbol table — must align with the descriptive slug → literal token used
	// by the MCP server and ssl-docs naming scheme.
	symbols := map[string]string{
		"add-assign":            "+=",
		"subtract-assign":       "-=",
		"multiply-assign":       "*=",
		"divide-assign":         "/=",
		"modulo-assign":         "%=",
		"power-assign":          "^=",
		"assignment":            ":=",
		"plus":                  "+",
		"minus":                 "-",
		"multiply":              "*",
		"divide":                "/",
		"modulo":                "%",
		"power":                 "^",
		"double-star-power":     "**",
		"increment":             "++",
		"decrement":             "--",
		"equals":                "=",
		"strict-equals":         "==",
		"not-equals":            "!=",
		"not-equals-legacy":     "<>",
		"hash":                  "#",
		"less-than":             "<",
		"greater-than":          ">",
		"less-than-or-equal":    "<=",
		"greater-than-or-equal": ">=",
		"and":                   ".AND.",
		"or":                    ".OR.",
		"not":                   ".NOT.",
		"bang":                  "!",
		"dollar":                "$",
		"shift-left":            "<<",
		"shift-right":           ">>",
	}

	var buf bytes.Buffer
	writeHeader(&buf, "Generated operator inventory and type-behavior tables (32 operators).")

	buf.WriteString("// GeneratedOperatorDetails maps each operator slug (e.g. \"add-assign\") to its symbol and behavior.\n")
	buf.WriteString("var GeneratedOperatorDetails = map[string]OperatorDetails{\n")
	for _, slug := range canonicalSorted(ref.Operators) {
		entry := ref.Operators[slug]
		sym := symbols[slug]
		fmt.Fprintf(&buf, "\t%s: {\n", quote(slug))
		fmt.Fprintf(&buf, "\t\tSymbol:  %s,\n", quote(sym))
		fmt.Fprintf(&buf, "\t\tTitle:   %s,\n", quote(entry.Title))
		fmt.Fprintf(&buf, "\t\tSummary: %s,\n", quote(entry.Summary))
		if entry.Syntax != "" {
			fmt.Fprintf(&buf, "\t\tSyntax:  %s,\n", quote(entry.Syntax))
		}
		if len(entry.TypeBehavior) > 0 {
			buf.WriteString("\t\tTypeBehavior: []OperatorTypeBehavior{\n")
			for _, row := range entry.TypeBehavior {
				fmt.Fprintf(&buf, "\t\t\t{Left: %s, Right: %s, Result: %s, Behavior: %s},\n",
					quote(cell(row, "left")),
					quote(cell(row, "right")),
					quote(cell(row, "result")),
					quote(cell(row, "behavior")))
			}
			buf.WriteString("\t\t},\n")
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n\n")

	buf.WriteString("// GeneratedOperatorBySymbol indexes operator details by their literal symbol.\n")
	buf.WriteString("var GeneratedOperatorBySymbol = map[string]OperatorDetails{}\n\n")
	buf.WriteString("func init() {\n")
	buf.WriteString("\tfor _, det := range GeneratedOperatorDetails {\n")
	buf.WriteString("\t\tif det.Symbol != \"\" {\n")
	buf.WriteString("\t\t\tGeneratedOperatorBySymbol[det.Symbol] = det\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n")
	return buf.Bytes()
}

func emitLiterals(ref *referenceFile) []byte {
	var buf bytes.Buffer
	writeHeader(&buf, "Generated literal inventory (3 literals).")

	buf.WriteString("// GeneratedLiteralDetails maps each literal slug (\"true\", \"false\", \"nil\") to its details.\n")
	buf.WriteString("var GeneratedLiteralDetails = map[string]LiteralDetails{\n")
	for _, k := range canonicalSorted(ref.Literals) {
		entry := ref.Literals[k]
		fmt.Fprintf(&buf, "\t%s: {\n", quote(k))
		fmt.Fprintf(&buf, "\t\tTitle:   %s,\n", quote(entry.Title))
		fmt.Fprintf(&buf, "\t\tSummary: %s,\n", quote(entry.Summary))
		if entry.Syntax != "" {
			fmt.Fprintf(&buf, "\t\tSyntax:  %s,\n", quote(entry.Syntax))
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")
	return buf.Bytes()
}

func emitTypes(ref *referenceFile) []byte {
	var buf bytes.Buffer
	writeHeader(&buf, "Generated type inventory and members (8 core SSL value types).")

	buf.WriteString("// GeneratedTypeDetails maps each core SSL type name (lowercase) to its members and operators.\n")
	buf.WriteString("var GeneratedTypeDetails = map[string]TypeDetails{\n")
	for _, k := range canonicalSorted(ref.Types) {
		entry := ref.Types[k]
		fmt.Fprintf(&buf, "\t%s: {\n", quote(k))
		fmt.Fprintf(&buf, "\t\tTitle:       %s,\n", quote(entry.Title))
		fmt.Fprintf(&buf, "\t\tSummary:     %s,\n", quote(entry.Summary))
		if entry.RuntimeType != "" {
			fmt.Fprintf(&buf, "\t\tRuntimeType: %s,\n", quote(entry.RuntimeType))
		}
		if len(entry.Operators) > 0 {
			buf.WriteString("\t\tOperators: []TypeOperatorRow{\n")
			for _, row := range entry.Operators {
				fmt.Fprintf(&buf, "\t\t\t{Operator: %s, Symbol: %s, Returns: %s, Behavior: %s},\n",
					quote(cell(row, "operator")),
					quote(cell(row, "symbol")),
					quote(cell(row, "returns")),
					quote(cell(row, "behavior")))
			}
			buf.WriteString("\t\t},\n")
		}
		if len(entry.Members) > 0 {
			buf.WriteString("\t\tMembers: []TypeMember{\n")
			for _, row := range entry.Members {
				fmt.Fprintf(&buf, "\t\t\t{Name: %s, Kind: %s, Returns: %s, Description: %s, Group: %s},\n",
					quote(cell(row, "member", "name")),
					quote(cell(row, "kind")),
					quote(cell(row, "returns")),
					quote(cell(row, "description")),
					quote(cell(row, "group")))
			}
			buf.WriteString("\t\t},\n")
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")
	return buf.Bytes()
}

func emitClasses(ref *referenceFile) []byte {
	var buf bytes.Buffer
	writeHeader(&buf, "Generated class inventory: constructors, methods, properties (29 classes).")

	buf.WriteString("// GeneratedClassNames is the canonical PascalCase list of built-in SSL classes.\n")
	buf.WriteString("var GeneratedClassNames = []string{\n")
	for _, k := range canonicalSorted(ref.Classes) {
		fmt.Fprintf(&buf, "\t%s,\n", quote(k))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("// GeneratedClassDetails maps each class name (lowercase) to its constructors, properties, and methods.\n")
	buf.WriteString("var GeneratedClassDetails = map[string]ClassDetails{\n")
	for _, k := range canonicalSorted(ref.Classes) {
		entry := ref.Classes[k]
		fmt.Fprintf(&buf, "\t%s: {\n", quote(strings.ToLower(k)))
		fmt.Fprintf(&buf, "\t\tTitle:   %s,\n", quote(entry.Title))
		fmt.Fprintf(&buf, "\t\tSummary: %s,\n", quote(entry.Summary))
		if entry.BaseClass != "" {
			fmt.Fprintf(&buf, "\t\tBaseClass: %s,\n", quote(entry.BaseClass))
		}
		if len(entry.Constructors) > 0 {
			buf.WriteString("\t\tConstructors: []ConstructorSignature{\n")
			for _, c := range entry.Constructors {
				buf.WriteString("\t\t\t{\n")
				fmt.Fprintf(&buf, "\t\t\t\tSignature: %s,\n", quote(c.Signature))
				if c.Description != "" {
					fmt.Fprintf(&buf, "\t\t\t\tDescription: %s,\n", quote(c.Description))
				}
				if len(c.Parameters) > 0 {
					buf.WriteString("\t\t\t\tParameters: []FunctionParameter{\n")
					for _, p := range c.Parameters {
						required := strings.EqualFold(cell(p, "required"), "yes")
						fmt.Fprintf(&buf, "\t\t\t\t\t{Name: %s, Type: %s, Required: %t, Description: %s},\n",
							quote(cell(p, "parameter", "name")),
							quote(cell(p, "type")),
							required,
							quote(cell(p, "description")))
					}
					buf.WriteString("\t\t\t\t},\n")
				}
				buf.WriteString("\t\t\t},\n")
			}
			buf.WriteString("\t\t},\n")
		}
		if len(entry.Properties) > 0 {
			buf.WriteString("\t\tProperties: []ClassProperty{\n")
			for _, p := range entry.Properties {
				fmt.Fprintf(&buf, "\t\t\t{Name: %s, Type: %s, Access: %s, Description: %s},\n",
					quote(cell(p, "name")),
					quote(cell(p, "type")),
					quote(cell(p, "access")),
					quote(cell(p, "description")))
			}
			buf.WriteString("\t\t},\n")
		}
		if len(entry.Methods) > 0 {
			buf.WriteString("\t\tMethods: []ClassMethod{\n")
			for _, m := range entry.Methods {
				fmt.Fprintf(&buf, "\t\t\t{Name: %s, Returns: %s, Description: %s},\n",
					quote(cell(m, "name")),
					quote(cell(m, "returns")),
					quote(cell(m, "description")))
			}
			buf.WriteString("\t\t},\n")
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")
	return buf.Bytes()
}

func emitFunctions(ref *referenceFile) []byte {
	var buf bytes.Buffer
	writeHeader(&buf, "Generated function inventory (330 functions). Curated signatures with parameter detail still live in signatures.go and overlay these names in canonical.go.")

	buf.WriteString("// GeneratedFunctionNames is the canonical PascalCase list of built-in SSL functions.\n")
	buf.WriteString("var GeneratedFunctionNames = []string{\n")
	for _, k := range canonicalSorted(ref.Functions) {
		fmt.Fprintf(&buf, "\t%s,\n", quote(k))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("// GeneratedFunctionSummaries maps each function (lowercase) to its published one-line summary and signature.\n")
	buf.WriteString("// Used as a fallback when signatures.go has no curated entry for a name.\n")
	buf.WriteString("var GeneratedFunctionSummaries = map[string]struct {\n")
	buf.WriteString("\tTitle     string\n")
	buf.WriteString("\tSummary   string\n")
	buf.WriteString("\tSignature string\n")
	buf.WriteString("\tReturns   string\n")
	buf.WriteString("}{\n")
	for _, k := range canonicalSorted(ref.Functions) {
		entry := ref.Functions[k]
		fmt.Fprintf(&buf, "\t%s: {\n", quote(strings.ToLower(k)))
		fmt.Fprintf(&buf, "\t\tTitle:     %s,\n", quote(entry.Title))
		fmt.Fprintf(&buf, "\t\tSummary:   %s,\n", quote(entry.Summary))
		if entry.Signature != "" {
			fmt.Fprintf(&buf, "\t\tSignature: %s,\n", quote(entry.Signature))
		}
		if entry.Returns != nil && entry.Returns.Type != "" {
			fmt.Fprintf(&buf, "\t\tReturns:   %s,\n", quote(entry.Returns.Type))
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")
	return buf.Bytes()
}

func emitSpecialForms(ref *referenceFile) []byte {
	var buf bytes.Buffer
	writeHeader(&buf, "Generated special-form inventory (6 special forms).")

	buf.WriteString("// GeneratedSpecialFormDetails maps each special-form slug to its details.\n")
	buf.WriteString("var GeneratedSpecialFormDetails = map[string]SpecialFormDetails{\n")
	for _, k := range canonicalSorted(ref.SpecialForms) {
		entry := ref.SpecialForms[k]
		fmt.Fprintf(&buf, "\t%s: {\n", quote(k))
		fmt.Fprintf(&buf, "\t\tTitle:   %s,\n", quote(entry.Title))
		fmt.Fprintf(&buf, "\t\tSummary: %s,\n", quote(entry.Summary))
		if entry.Syntax != "" {
			fmt.Fprintf(&buf, "\t\tSyntax:  %s,\n", quote(entry.Syntax))
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")
	return buf.Bytes()
}
