// Code generated by cmd/gen-inventory; DO NOT EDIT.
// Source: internal/constants/data/ssl-element-reference.json

package constants

// Generated class inventory: constructors, methods, properties (29 classes).

// GeneratedClassNames is the canonical PascalCase list of built-in SSL classes.
var GeneratedClassNames = []string{
	"AzureStorage",
	"BatchSupport",
	"CDataColumn",
	"CDataColumns",
	"CDataField",
	"CDataRow",
	"CDataTable",
	"Email",
	"EnterpriseExporter",
	"FtpsClient",
	"HtmlConverter",
	"PatcherSupport",
	"PdfSupport",
	"RegSetup",
	"SDMS",
	"SDMSDocUploader",
	"Sequence",
	"SQLConnection",
	"SSLBaseDictionary",
	"SSLCodeProvider",
	"SSLDataset",
	"SSLError",
	"SSLExpando",
	"SSLIntDictionary",
	"SSLRegex",
	"SSLSQLError",
	"SSLStringDictionary",
	"TablesImport",
	"WebServices",
}

// GeneratedClassDetails maps each class name (lowercase) to its constructors, properties, and methods.
var GeneratedClassDetails = map[string]ClassDetails{
	"azurestorage": {
		Title:   "AzureStorage",
		Summary: "Provides SSL access to Azure Table Storage and Azure Blob Storage through one class.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "AzureStorage{}",
				Description: "Uses the first configured Azure connection available to the application.",
			},
			{
				Signature:   "AzureStorage{sConnectionName}",
				Description: "Uses the named Azure connection from the application configuration.",
				Parameters: []FunctionParameter{
					{Name: "sConnectionName", Type: "string", Required: true, Description: "Name of the configured Azure connection to use."},
				},
			},
			{
				Signature:   "AzureStorage{sAccountName, sAccountKey}",
				Description: "Creates the client from an explicit Azure account name and key.",
				Parameters: []FunctionParameter{
					{Name: "sAccountName", Type: "string", Required: true, Description: "Azure storage account name."},
					{Name: "sAccountKey", Type: "string", Required: true, Description: "Azure storage account key."},
				},
			},
			{
				Signature:   "AzureStorage{sAccountName, sAccountKey, bUseHttp}",
				Description: "Creates the client from an explicit Azure account name and key.",
				Parameters: []FunctionParameter{
					{Name: "sAccountName", Type: "string", Required: true, Description: "Azure storage account name."},
					{Name: "sAccountKey", Type: "string", Required: true, Description: "Azure storage account key."},
					{Name: "bUseHttp", Type: "boolean", Required: false, Description: "Despite the parameter name, passing .T. uses HTTPS and .F. uses HTTP."},
				},
			},
		},
		Methods: []ClassMethod{
			{Name: "CreateTable", Returns: "none", Description: "Creates a table if needed."},
			{Name: "DeleteTable", Returns: "none", Description: "Deletes a table if it exists."},
			{Name: "InsertEntity", Returns: "none", Description: "Inserts one table entity."},
			{Name: "InsertEntities", Returns: "none", Description: "Inserts multiple table entities in batches."},
			{Name: "SelectEntity", Returns: "object", Description: "Returns one entity or NIL when not found."},
			{Name: "SelectEntities", Returns: "array", Description: "Returns entities that match an equality-based filter."},
			{Name: "DeleteEntity", Returns: "none", Description: "Deletes one entity if it exists."},
			{Name: "DeleteEntities", Returns: "none", Description: "Deletes multiple entities in batches."},
			{Name: "UpdateEntity", Returns: "boolean", Description: "Updates one entity and reports success."},
			{Name: "CreateContainer", Returns: "none", Description: "Creates a blob container if needed."},
			{Name: "DeleteContainer", Returns: "none", Description: "Deletes a blob container if it exists."},
			{Name: "PutBlob", Returns: "none", Description: "Uploads a local file as a blob."},
			{Name: "GetBlob", Returns: "string", Description: "Downloads a blob and returns the local file path."},
			{Name: "DeleteBlob", Returns: "none", Description: "Deletes a blob."},
			{Name: "ReadBlobAsText", Returns: "string", Description: "Returns blob contents as text."},
		},
	},
	"batchsupport": {
		Title:   "BatchSupport",
		Summary: "Provides batch-status checks and memory usage information for the current SSL process.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "BatchSupport{}",
				Description: "Creates a `BatchSupport` instance bound to the current SSL process so its memory properties can be read.",
			},
		},
		Properties: []ClassProperty{
			{Name: "ActiveBatchesNumber", Type: "number", Access: "read-only", Description: "Number of active batches in the current application."},
			{Name: "PhysicalMemory", Type: "number", Access: "read-only", Description: "Current process physical memory usage in bytes. Returns -1 after Dispose()."},
			{Name: "VirtualMemory", Type: "number", Access: "read-only", Description: "Current process virtual memory usage in bytes. Returns -1 after Dispose()."},
		},
		Methods: []ClassMethod{
			{Name: "Dispose", Returns: "none", Description: "Releases the instance's process resources."},
			{Name: "IsRunning", Returns: "boolean", Description: "Checks whether a named batch or integer process ID is currently running."},
		},
	},
	"cdatacolumn": {
		Title:   "CDataColumn",
		Summary: "Provides metadata for a single column in a CDataTable.",
		Properties: []ClassProperty{
			{Name: "DBType", Type: "number", Access: "read-only", Description: "Numeric type code for the column. Unknown types return 0."},
			{Name: "FType", Type: "string", Access: "read-only", Description: "Type label for the column, such as SQL_INTEGER, SQL_VARCHAR, SQL_DATE, or SQL_BINARY. Unknown types return an empty string."},
			{Name: "IsBlob", Type: "boolean", Access: "read-only", Description: ".T. when the column stores binary data."},
			{Name: "IsPk", Type: "boolean", Access: "read-only", Description: ".T. when the column is part of the table's current primary key."},
			{Name: "Length", Type: "number", Access: "read-write", Description: "Maximum length for the column."},
			{Name: "Name", Type: "string", Access: "read-write", Description: "Column name."},
			{Name: "Scale", Type: "number", Access: "read-only", Description: "Always returns 0."},
		},
	},
	"cdatacolumns": {
		Title:   "CDataColumns",
		Summary: "Provides access to the column definitions of a CDataTable.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "CDataColumns{oDataTable}",
				Description: "| Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `oDataTable` | object | yes | The `CDataTable` whose columns are exposed by the collection. In most scripts, use `oTable:Columns` instead of constructing the collection directly. |",
				Parameters: []FunctionParameter{
					{Name: "oDataTable", Type: "object", Required: true, Description: "The CDataTable whose columns are exposed by the collection. In most scripts, use oTable:Columns instead of constructing the collection directly."},
				},
			},
		},
		Properties: []ClassProperty{
			{Name: "Count", Type: "number", Access: "read-only", Description: "Number of columns in the collection."},
			{Name: "ParentTable", Type: "object", Access: "write-only", Description: "Assigns a parent CDataTable to the collection. The assigned value is not readable from SSL."},
		},
		Methods: []ClassMethod{
			{Name: "Add", Returns: "none", Description: "Accepts a column argument, but does not add it to the collection."},
			{Name: "GetIndex", Returns: "number", Description: "Returns the 1-based position of a named column, or 0 if it is not found."},
			{Name: "Set", Returns: "NIL", Description: "Accepts an index and column argument, but does not update the collection."},
			{Name: "Get", Returns: "object", Description: "Returns a CDataColumn by name or by 1-based index."},
		},
	},
	"cdatafield": {
		Title:   "CDataField",
		Summary: "Represents one field in a CDataRow.",
		Properties: []ClassProperty{
			{Name: "IsNull", Type: "boolean", Access: "read-only", Description: ".T. when the field value is null"},
			{Name: "Value", Type: "any", Access: "read-write", Description: "Gets or sets the field value. For binary fields, reading returns a file path and writing expects a file path instead of raw bytes."},
		},
	},
	"cdatarow": {
		Title:   "CDataRow",
		Summary: "Represents one row in a CDataTable.",
		Properties: []ClassProperty{
			{Name: "Table", Type: "object", Access: "read-only", Description: "Parent CDataTable for this row."},
		},
	},
	"cdatatable": {
		Title:   "CDataTable",
		Summary: "Provides an in-memory table object for working with rows, columns, XML, and database persistence from SSL.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "CDataTable{}",
				Description: "Creates an empty table.",
			},
			{
				Signature:   "CDataTable{oDataTable, sImportFolder}",
				Description: "Wraps an existing table object and associates an import folder with it.",
				Parameters: []FunctionParameter{
					{Name: "oDataTable", Type: "object", Required: true, Description: "Existing table handle."},
					{Name: "sImportFolder", Type: "string", Required: true, Description: "Folder used for imported table assets such as extracted binary values."},
				},
			},
			{
				Signature:   "CDataTable{sName, nColCount}",
				Description: "Creates an empty named table.",
				Parameters: []FunctionParameter{
					{Name: "sName", Type: "string", Required: true, Description: "Table name."},
					{Name: "nColCount", Type: "number", Required: true, Description: "Accepted by the constructor, but it does not define the schema."},
				},
			},
		},
		Properties: []ClassProperty{
			{Name: "Columns", Type: "object", Access: "read-only", Description: "CDataColumns collection for the current schema."},
			{Name: "ErrMsg", Type: "string", Access: "read-only", Description: "Error text property exposed by the class. The documented methods on this page do not populate it."},
			{Name: "ImportFolder", Type: "string", Access: "read-write", Description: "Folder associated with imported content and extracted binary values. Setting it to NIL clears it to an empty string."},
			{Name: "InnerTable", Type: "object", Access: "read-only", Description: "Underlying table handle for advanced integration scenarios."},
			{Name: "IsSystem", Type: "boolean", Access: "read-write", Description: "Controls whether generated SQL and persistence target system-table context."},
			{Name: "Name", Type: "string", Access: "read-write", Description: "Table name."},
			{Name: "NullAsBlank", Type: "boolean", Access: "read-write", Description: "Controls whether null values are converted to blank or default values in array and XML conversions."},
			{Name: "PkColumns", Type: "array", Access: "read-only", Description: "Array of CDataColumn objects that make up the primary key."},
			{Name: "Rows", Type: "array", Access: "read-only", Description: "Array of CDataRow objects for all rows in the table."},
			{Name: "RowsCount", Type: "number", Access: "read-only", Description: "Number of rows in the table."},
		},
		Methods: []ClassMethod{
			{Name: "AddPK", Returns: "boolean", Description: "Assigns one or more columns as the table's primary key."},
			{Name: "AddRow", Returns: "none", Description: "Appends an existing CDataRow to the table."},
			{Name: "NewRow", Returns: "object", Description: "Creates a new unattached CDataRow for this table."},
			{Name: "GetInsertSql", Returns: "string", Description: "Returns an INSERT statement for the current schema, excluding binary columns."},
			{Name: "GetUpdateSql", Returns: "string", Description: "Returns an UPDATE statement for the current schema, using primary-key columns in the WHERE clause and excluding binary columns."},
			{Name: "SaveToDb", Returns: "boolean", Description: "Persists current rows, or a selected subset of current rows, to the database."},
			{Name: "Select", Returns: "array", Description: "Returns matching CDataRow objects."},
			{Name: "ToArray", Returns: "array", Description: "Returns the table as a 2D array of values."},
			{Name: "ToXml", Returns: "string", Description: "Serializes the table, including schema, to XML."},
			{Name: "UpdateField", Returns: "boolean", Description: "Replaces one field value across matching rows."},
			{Name: "UpdateFieldFromArray", Returns: "boolean", Description: "Replaces field values by key lookup from an array of {newValue, key} pairs."},
			{Name: "FromXml", Returns: "NIL", Description: "Replaces the current table with the first table read from XML."},
		},
	},
	"email": {
		Title:   "Email",
		Summary: "Composes, loads, saves, sends, or queues email messages with attachments and optional signing or encryption.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "Email{}",
				Description: "Creates an `Email` object with exception suppression enabled by default. Operations return `.T.` or `.F.`, and failures are exposed through the `Exception` property.",
			},
			{
				Signature:   "Email{bIgnoreExceptions}",
				Description: "| Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `bIgnoreExceptions` | boolean | yes | When `.T.`, methods suppress exceptions and return `.F.` on failure. When `.F.`, failures raise exceptions. |",
				Parameters: []FunctionParameter{
					{Name: "bIgnoreExceptions", Type: "boolean", Required: true, Description: "When .T., methods suppress exceptions and return .F. on failure. When .F., failures raise exceptions."},
				},
			},
		},
		Properties: []ClassProperty{
			{Name: "Attachments", Type: "array", Access: "read-write", Description: "File paths to attach when building the message."},
			{Name: "BCC", Type: "array", Access: "read-write", Description: "Blind carbon copy recipients."},
			{Name: "Body", Type: "string", Access: "read-write", Description: "Message body text."},
			{Name: "CC", Type: "array", Access: "read-write", Description: "Carbon copy recipients."},
			{Name: "Exception", Type: "SSLError", Access: "read-only", Description: "Most recent failure captured by the object."},
			{Name: "From", Type: "string", Access: "read-write", Description: "Sender address."},
			{Name: "IgnoreExceptions", Type: "boolean", Access: "read-write", Description: "Controls whether failures are suppressed or raised."},
			{Name: "IsHTMLBody", Type: "boolean", Access: "read-write", Description: "When .T., the body is sent as HTML as well as plain text."},
			{Name: "LogSMTP", Type: "boolean", Access: "read-write", Description: "Writes an SMTP session log for direct Send calls."},
			{Name: "SMTPServerName", Type: "string", Access: "read-write", Description: "SMTP server host name."},
			{Name: "SMTPServerPort", Type: "number", Access: "read-write", Description: "SMTP server port."},
			{Name: "SMTPSecureConnection", Type: "boolean", Access: "read-write", Description: "Enables a secure SMTP connection."},
			{Name: "SMTPServerUserName", Type: "string", Access: "read-write", Description: "SMTP login user name."},
			{Name: "SMTPServerUserPassword", Type: "string", Access: "read-write", Description: "SMTP login password."},
			{Name: "SMTPTimeout", Type: "number", Access: "read-write", Description: "Timeout in seconds for direct Send calls. 0 uses the default timeout."},
			{Name: "Subject", Type: "string", Access: "read-write", Description: "Message subject."},
			{Name: "To", Type: "array", Access: "read-write", Description: "Primary recipients."},
		},
		Methods: []ClassMethod{
			{Name: "LoadMessage", Returns: "boolean", Description: "Loads a message file for later Send."},
			{Name: "SaveMessage", Returns: "boolean", Description: "Saves the current message to a file in message format."},
			{Name: "Send", Returns: "boolean", Description: "Sends the current message through SMTP."},
			{Name: "SendToOutbox", Returns: "boolean", Description: "Queues the current message for later delivery."},
			{Name: "SetEncryptCertificateFromPath", Returns: "boolean", Description: "Loads the encryption certificate from a file."},
			{Name: "SetEncryptCertificateFromStore", Returns: "boolean", Description: "Loads the encryption certificate from a certificate store."},
			{Name: "SetSignCertificateFromPath", Returns: "boolean", Description: "Loads the signing certificate from a file."},
			{Name: "SetSignCertificateFromStore", Returns: "boolean", Description: "Loads the signing certificate from a certificate store."},
		},
	},
	"enterpriseexporter": {
		Title:     "EnterpriseExporter",
		Summary:   "Exports tables into a destination folder.",
		BaseClass: "EnterpriseImpExBase",
		Constructors: []ConstructorSignature{
			{
				Signature:   "EnterpriseExporter{aTables, bSysTables, sPath}",
				Description: "| Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `aTables` | array | yes | Table list. Use a simple array of table names in default mode, or an array of table entries in `IsEnterpriseOnly` and `FromSQL` modes. In entry-based modes, each entry starts with the output table name and can include a second string value used as the source string for that table. | | `bSysTables` | boolean | yes | When `.T.`, exports system-table content instead of regular table content. | | `sPath` | string | yes | Destination folder for the export output. The exporter writes one subfolder and one `.txt` file per table. |",
				Parameters: []FunctionParameter{
					{Name: "aTables", Type: "array", Required: true, Description: "Table list. Use a simple array of table names in default mode, or an array of table entries in IsEnterpriseOnly and FromSQL modes. In entry-based modes, each entry starts with the output table name and can include a second string value used as the source string for that table."},
					{Name: "bSysTables", Type: "boolean", Required: true, Description: "When .T., exports system-table content instead of regular table content."},
					{Name: "sPath", Type: "string", Required: true, Description: "Destination folder for the export output. The exporter writes one subfolder and one .txt file per table."},
				},
			},
		},
		Properties: []ClassProperty{
			{Name: "AbortOnError", Type: "boolean", Access: "read-write", Description: "Writable flag on the class. In practice, setting it does not change DoExport() behavior."},
			{Name: "LogFile", Type: "string", Access: "read-write", Description: "Log file path or \"console\" for console logging."},
			{Name: "IsEnterpriseOnly", Type: "boolean", Access: "write-only", Description: "Switches the export to enterprise-only mode, where each table entry can supply a custom FROM source."},
			{Name: "FromSQL", Type: "boolean", Access: "write-only", Description: "Switches the export to SQL mode, where each table entry can supply a full SQL statement."},
			{Name: "NullAsBlank", Type: "boolean", Access: "write-only", Description: "In SQL mode, controls whether exported NULL values are treated as blanks. Defaults to .F.."},
			{Name: "InvariantDateColumns", Type: "array", Access: "write-only", Description: "In SQL mode, supplies the invariant date columns passed to the export operation."},
		},
		Methods: []ClassMethod{
			{Name: "DoExport", Returns: "boolean", Description: "Runs the export and returns the completion result from the underlying export process. It also updates ErrorMsg with the final exporter message when the call returns normally."},
		},
	},
	"ftpsclient": {
		Title:   "FtpsClient",
		Summary: "Transfers files and manages directories on an FTPS server.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "FtpsClient{}",
				Description: "Creates a new FTPS client instance.",
			},
		},
	},
	"htmlconverter": {
		Title:   "HtmlConverter",
		Summary: "Converts XFD form XML into HTML form XML and exposes the most recent conversion log.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "HtmlConverter{}",
				Description: "Creates a converter with default conversion options and an empty log.",
			},
		},
		Properties: []ClassProperty{
			{Name: "OptionsXml", Type: "string", Access: "write-only", Description: "Sets the conversion option XML used by subsequent Convert calls"},
			{Name: "Log", Type: "string", Access: "read-only", Description: "Returns the full text of the current conversion log"},
			{Name: "SimplifiedLog", Type: "string", Access: "read-only", Description: "Returns a shorter summary of the current conversion log with repeated conversion messages collapsed"},
		},
		Methods: []ClassMethod{
			{Name: "Convert", Returns: "string", Description: "Converts XFD form XML to HTML form XML using the supplied source and target form IDs"},
			{Name: "ClearLog", Returns: "none", Description: "Resets the current log to empty"},
		},
	},
	"patchersupport": {
		Title:   "PatcherSupport",
		Summary: "Provides helper methods for collecting package-style dictionary metadata, connecting to another STARLIMS system, and comparing one collected result table to another.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "PatcherSupport{}",
				Description: "Creates a new `PatcherSupport` object with an empty result table.",
			},
		},
		Properties: []ClassProperty{
			{Name: "DiffDataTable", Type: "string", Access: "read-only", Description: "Serialized dataset string produced by the most recent successful Compare() call. Empty until a comparison serializes the current result table."},
			{Name: "InternalErrors", Type: "string", Access: "read-only", Description: "Accumulated error text captured when log-file setup fails or when metadata retrieval calls fail while collecting forms, scripts, data sources, or tables."},
			{Name: "LogFilePath", Type: "string", Access: "read-write", Description: "Current log file path. Setting it attempts to create or replace the file and resets the active trace listeners to write to that file."},
			{Name: "ResultTable", Type: "object", Access: "read-only", Description: "Current package table used for collected dictionary metadata and later comparison results."},
		},
	},
	"pdfsupport": {
		Title:   "PdfSupport",
		Summary: "Provides methods to create, modify, secure, save, and print PDF documents.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "PdfSupport{}",
				Description: "Creates a new empty PDF document. New instances use a default text style of Verdana, size 20, in black.",
			},
		},
		Properties: []ClassProperty{
			{Name: "PageCount", Type: "number", Access: "read-only", Description: "The total number of pages in the PDF document."},
			{Name: "UserPassword", Type: "string", Access: "write-only", Description: "The user password required to open the PDF document."},
			{Name: "OwnerPassword", Type: "string", Access: "write-only", Description: "The owner password for the PDF document that controls permissions."},
			{Name: "DocumentSecurityLevel", Type: "string", Access: "read-write", Description: "The document security level. Valid values are None, Encrypted40Bit, and Encrypted128Bit."},
			{Name: "PermitAccessibilityExtractContent", Type: "boolean", Access: "read-write", Description: "Whether content extraction for accessibility is permitted."},
			{Name: "PermitAnnotations", Type: "boolean", Access: "read-write", Description: "Whether adding or modifying annotations is permitted."},
			{Name: "PermitAssembleDocument", Type: "boolean", Access: "read-write", Description: "Whether assembling the document (inserting, rotating, or deleting pages) is permitted."},
			{Name: "PermitExtractContent", Type: "boolean", Access: "read-write", Description: "Whether extracting text and graphics is permitted."},
			{Name: "PermitFormsFill", Type: "boolean", Access: "read-write", Description: "Whether filling form fields is permitted."},
			{Name: "PermitFullQualityPrint", Type: "boolean", Access: "read-write", Description: "Whether printing to full quality is permitted."},
			{Name: "PermitModifyDocument", Type: "boolean", Access: "read-write", Description: "Whether modifying the document content is permitted."},
			{Name: "PermitPrint", Type: "boolean", Access: "read-write", Description: "Whether printing the document is permitted."},
		},
		Methods: []ClassMethod{
			{Name: "AddPageFromImage", Returns: "none", Description: "Adds a new page from an image file."},
			{Name: "AddPDFDocument", Returns: "none", Description: "Imports all pages from another PDF."},
			{Name: "AddTextOnPage", Returns: "none", Description: "Draws text on an existing page using the current text style."},
			{Name: "SetTextStyle", Returns: "none", Description: "Sets the text style used for later text drawing."},
			{Name: "Open", Returns: "none", Description: "Opens an existing PDF for modification."},
			{Name: "OpenProtectedDocument", Returns: "none", Description: "Opens a password-protected PDF for modification."},
			{Name: "Save", Returns: "none", Description: "Saves the current PDF document to a file."},
			{Name: "Print", Returns: "none", Description: "Prints a specified PDF file to a named printer."},
			{Name: "Protect", Returns: "none", Description: "Applies a predefined security profile to the current PDF document."},
		},
	},
	"regsetup": {
		Title:   "RegSetup",
		Summary: "Provides access to Windows registry values under HKEY_LOCAL_MACHINE.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "RegSetup{}",
				Description: "Creates a `RegSetup` instance with no open registry key.",
			},
		},
		Methods: []ClassMethod{
			{Name: "RegOpenKey", Returns: "boolean", Description: "Opens a subkey under HKEY_LOCAL_MACHINE."},
			{Name: "RegQueryValue", Returns: "object", Description: "Reads a value from the currently open key."},
			{Name: "RegCloseKey", Returns: "boolean", Description: "Closes the current key handle."},
		},
	},
	"sdms": {
		Title:   "SDMS",
		Summary: "Interacts with an external SDMS server to download documents, download Unified XML templates, create an SDMSDocUploader, and generate password hashes for SDMS authentication.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "SDMS{}",
				Description: "Creates an instance without loading connection settings.",
			},
			{
				Signature:   "SDMS{oCredentials}",
				Description: "Creates an instance and reads connection settings from `oCredentials`.",
				Parameters: []FunctionParameter{
					{Name: "oCredentials", Type: "object", Required: true, Description: "Object that supplies the SDMS connection properties used by the class."},
				},
			},
		},
		Properties: []ClassProperty{
			{Name: "ErrorMessage", Type: "string", Access: "read-only", Description: "Error text from the most recent failed download, check-out, or template download request."},
			{Name: "IsSessionExpired", Type: "boolean", Access: "read-only", Description: "Indicates whether the most recent download, check-out, or template download failed because the SDMS session expired."},
			{Name: "SessionId", Type: "string", Access: "read-write", Description: "Session ID to send with requests when it is not empty."},
		},
		Methods: []ClassMethod{
			{Name: "CheckOutDocument", Returns: "boolean", Description: "Downloads the NewRevision version of a document to sDestinationPath."},
			{Name: "CreateDocUploader", Returns: "SDMSDocUploader", Description: "Creates an SDMSDocUploader using the supplied credentials object."},
			{Name: "CreateUnifiedXmlDOM", Returns: "object", Description: "Creates and returns a Unified XML DOM object."},
			{Name: "DownloadDocument", Returns: "none", Description: "Deprecated. Always raises an exception."},
			{Name: "DownloadDocument2", Returns: "boolean", Description: "Downloads the specified document type to sDestinationPath."},
			{Name: "DownloadOriginalDocument", Returns: "none", Description: "Deprecated. Always raises an exception."},
			{Name: "DownloadOriginalDocument2", Returns: "boolean", Description: "Downloads the original document by calling DownloadDocument2(sDocId, \"ORG\", sDestinationPath)."},
			{Name: "DownloadUnifiedXmlDocument", Returns: "none", Description: "Deprecated. Always raises an exception."},
			{Name: "DownloadUnifiedXmlDocument2", Returns: "boolean", Description: "Downloads the Unified XML version by calling DownloadDocument2(sDocId, \"UXML\", sDestinationPath)."},
			{Name: "DownloadUnifiedXmlTemplate", Returns: "boolean", Description: "Downloads a Unified XML template by numeric template ID or by template name."},
			{Name: "GetHttpPassHash", Returns: "string", Description: "Converts a hexadecimal password string into the URL-encoded HTTP hash used by SDMS requests."},
			{Name: "GetSoapPassHash", Returns: "string", Description: "Converts a hexadecimal password string into the Base64 SOAP hash used by SDMS requests."},
			{Name: "SetSDMSConnection", Returns: "none", Description: "Deprecated. Always raises an exception."},
			{Name: "UploadDocument", Returns: "string", Description: "Deprecated. Always raises an exception before returning a value."},
		},
	},
	"sdmsdocuploader": {
		Title:   "SDMSDocUploader",
		Summary: "Uploads files into SDMS, attaches uploads to workflow steps, and checks in document revisions.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "SDMSDocUploader{oCredentials}",
				Description: "Creates an uploader and loads the SDMS URL, username, password hash, site ID, and session ID from the credentials object. Workflow IDs start in a missing state and must be set before workflow-specific calls.",
				Parameters: []FunctionParameter{
					{Name: "oCredentials", Type: "object", Required: true, Description: "Credentials object supplying SDMS URL, username, password hash, site ID, and session ID."},
				},
			},
			{
				Signature:   "SDMSDocUploader{}",
				Description: "Creates an uploader without loading SDMS connection or authentication values. Workflow IDs start at `0`, so the workflow-specific missing-ID validation described below does not run automatically unless you assign your own values.",
			},
		},
		Properties: []ClassProperty{
			{Name: "FilePath", Type: "string", Access: "read-write", Description: "Local path of the file to upload or attach."},
			{Name: "DocName", Type: "string", Access: "read-write", Description: "Document name sent to SDMS. For most upload methods, if this is blank it defaults to the file name from FilePath. CheckInDocument() still requires it to be set."},
			{Name: "DocId", Type: "number", Access: "read-write", Description: "Target SDMS document ID. Uploads that return a document ID also update this property from the SDMS response."},
			{Name: "FileType", Type: "string", Access: "read-write", Description: "SDMS file type value for upload requests. If blank, most upload methods use Default."},
			{Name: "ProjectName", Type: "string", Access: "read-write", Description: "SDMS project name for upload requests. If blank, most upload methods use DefaultProject."},
			{Name: "WorkflowId", Type: "number", Access: "read-write", Description: "Workflow identifier used by workflow-specific methods."},
			{Name: "StageId", Type: "number", Access: "read-write", Description: "Workflow stage identifier used by workflow-specific methods."},
			{Name: "ActionId", Type: "number", Access: "read-write", Description: "Workflow action identifier used by workflow-specific methods."},
			{Name: "Metadata", Type: "array", Access: "read-write", Description: "Array of {key, value} pairs used only by UploadOriginalDoc() when UXmlTemplate is also set."},
			{Name: "UXmlTemplate", Type: "string", Access: "read-write", Description: "UXML content used only by UploadOriginalDoc() when Metadata is also set."},
		},
		Methods: []ClassMethod{
			{Name: "UploadOriginalDoc", Returns: "boolean", Description: "Uploads the file as an original SDMS document."},
			{Name: "AttachDocToWorkflow", Returns: "boolean", Description: "Uploads the file and attaches it to the configured workflow, stage, and action."},
			{Name: "CheckInDocument", Returns: "boolean", Description: "Checks in a new revision for an existing SDMS document."},
			{Name: "AttachFileToDocument", Returns: "boolean", Description: "Attaches a file to an existing SDMS document."},
			{Name: "UploadOfficeTemplate", Returns: "boolean", Description: "Uploads the file as an Office template."},
			{Name: "UploadELNDocument", Returns: "boolean", Description: "Uploads the file as an ELN document."},
			{Name: "AddHeader", Returns: "none", Description: "Adds a custom header to later requests made by this uploader instance."},
			{Name: "RemoveHeader", Returns: "none", Description: "Removes a custom header from later requests made by this uploader instance."},
			{Name: "DoUpload", Returns: "number", Description: "Performs a low-level upload and returns the document ID on success."},
			{Name: "CheckInWorkflowDocument", Returns: "boolean", Description: "Adds workflow context, then checks in a document revision."},
			{Name: "UploadNewRevisionForWorkflowDocument", Returns: "boolean", Description: "Uploads a new workflow revision with version status newDoc."},
		},
	},
	"sequence": {
		Title:   "Sequence",
		Summary: "Creates and manages a database sequence for a table field on Oracle or SQL Server.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "Sequence{sPlatforma, sTableName, sFieldName}",
				Description: "Creates a sequence object with an empty prefix.",
				Parameters: []FunctionParameter{
					{Name: "sPlatforma", Type: "string", Required: true, Description: "Database platform. \"ORACLE\" selects Oracle behavior. Any other value uses SQL Server behavior."},
					{Name: "sTableName", Type: "string", Required: true, Description: "Table name used to derive the sequence name."},
					{Name: "sFieldName", Type: "string", Required: true, Description: "Field name used to derive the sequence name."},
				},
			},
			{
				Signature:   "Sequence{sPlatforma, sTableName, sFieldName, sPrefix}",
				Description: "Creates a sequence object with an additional name suffix.",
				Parameters: []FunctionParameter{
					{Name: "sPlatforma", Type: "string", Required: true, Description: "Database platform. \"ORACLE\" selects Oracle behavior. Any other value uses SQL Server behavior."},
					{Name: "sTableName", Type: "string", Required: true, Description: "Table name used to derive the sequence name."},
					{Name: "sFieldName", Type: "string", Required: true, Description: "Field name used to derive the sequence name."},
					{Name: "sPrefix", Type: "string", Required: false, Description: "Optional suffix added to the derived sequence name. If omitted or passed as NIL, an empty suffix is used."},
				},
			},
		},
		Properties: []ClassProperty{
			{Name: "SequenceName", Type: "string", Access: "read-only", Description: "Derived sequence name for the current table, field, and prefix."},
			{Name: "StartWith", Type: "number", Access: "read-write", Description: "First value used when Create() creates the sequence. Default is 1."},
			{Name: "CacheSize", Type: "number", Access: "read-write", Description: "Cache size used when SQL Server creates the sequence. Default is 50. Oracle creation ignores this property."},
			{Name: "Exists", Type: "boolean", Access: "read-only", Description: ".T. when the sequence exists in the current database."},
			{Name: "NextValue", Type: "number", Access: "read-only", Description: "Retrieves the next value from the current database sequence."},
		},
		Methods: []ClassMethod{
			{Name: "Create", Returns: "none", Description: "Creates the sequence in the current database."},
			{Name: "Reset", Returns: "none", Description: "Changes the next starting value for the sequence."},
			{Name: "Drop", Returns: "none", Description: "Drops the sequence from the current database."},
			{Name: "SetDatabase", Returns: "none", Description: "Changes the database used for later operations."},
		},
	},
	"sqlconnection": {
		Title:   "SQLConnection",
		Summary: "Represents a configured database connection returned by GetConnectionByName.",
		Properties: []ClassProperty{
			{Name: "DataSource", Type: "string", Access: "read-only", Description: "Server, DSN, or data source name from the connection string."},
			{Name: "DatabaseName", Type: "string", Access: "read-only", Description: "Database name for SQL Server connections. Oracle connections return \"Not Set\"."},
			{Name: "UserId", Type: "string", Access: "read-only", Description: "User name from the connection string."},
			{Name: "Password", Type: "string", Access: "read-only", Description: "Password from the connection string."},
			{Name: "Platforma", Type: "string", Access: "read-only", Description: "Database platform name, such as \"Microsoft SQL Server\"."},
			{Name: "ConnectionString", Type: "string", Access: "read-only", Description: "Full connection string for the connection."},
			{Name: "UseUTC", Type: "boolean", Access: "read-only", Description: "Whether the connection uses UTC timestamps."},
		},
	},
	"sslbasedictionary": {
		Title:   "SSLBaseDictionary",
		Summary: "Provides the shared dictionary surface used by SSL dictionary classes such as SSLStringDictionary{} and SSLIntDictionary{}.",
		Properties: []ClassProperty{
			{Name: "Count", Type: "number", Access: "read-only", Description: "Number of key-value pairs currently stored"},
			{Name: "Keys", Type: "array", Access: "read-only", Description: "Array containing the current keys"},
			{Name: "Values", Type: "array", Access: "read-only", Description: "Array containing the current values"},
		},
	},
	"sslcodeprovider": {
		Title:   "SSLCodeProvider",
		Summary: "Compiles published server scripts and data sources and returns a list of compilation errors.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "SSLCodeProvider{}",
				Description: "Creates a code provider instance.",
			},
		},
		Methods: []ClassMethod{
			{Name: "CompileAll", Returns: "object", Description: "Compiles all server scripts and data sources."},
			{Name: "CompileAllServerScripts", Returns: "object", Description: "Compiles all server scripts."},
			{Name: "CompileAllDataSources", Returns: "object", Description: "Compiles all data sources."},
			{Name: "CompileServerScript", Returns: "object", Description: "Compiles one server script by GUID or full name."},
			{Name: "CompileServerScripts", Returns: "object", Description: "Compiles multiple server scripts."},
			{Name: "CompileServerScriptCategory", Returns: "object", Description: "Compiles all server scripts in one category."},
			{Name: "CompileServerScriptCategories", Returns: "object", Description: "Compiles all server scripts in multiple categories."},
			{Name: "CompileDataSource", Returns: "object", Description: "Compiles one data source by GUID or full name."},
			{Name: "CompileDataSources", Returns: "object", Description: "Compiles multiple data sources."},
			{Name: "CompileDataSourceCategory", Returns: "object", Description: "Compiles all data sources in one category."},
			{Name: "CompileDataSourceCategories", Returns: "object", Description: "Compiles all data sources in multiple categories."},
			{Name: "CompileScript", Returns: "object", Description: "Accepts SSL code text, but currently raises a not-implemented error for non-null input."},
		},
	},
	"ssldataset": {
		Title:   "SSLDataset",
		Summary: "Represents dataset results so SSL code can work with query output as an object, convert the first table to an array, export XML, or pass the dataset handle to APIs that expect one.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "SSLDataset{}",
				Description: "Creates an empty dataset object with no loaded data.",
			},
			{
				Signature:   "SSLDataset{oData, bNullAsBlank}",
				Description: "Creates an `SSLDataset` from an existing dataset handle.",
				Parameters: []FunctionParameter{
					{Name: "oData", Type: "object", Required: true, Description: "Existing dataset handle."},
					{Name: "bNullAsBlank", Type: "boolean", Required: true, Description: "Controls how ToArray() represents null values from the first table. Pass .T. to convert nulls to blank values, or .F. to preserve nulls."},
				},
			},
		},
		Methods: []ClassMethod{
			{Name: "ToXml", Returns: "string", Description: "Serializes the current dataset to XML with schema and an XML declaration."},
			{Name: "ToArray", Returns: "array", Description: "Returns the first table as an array of rows."},
			{Name: "ToDataSet", Returns: "object", Description: "Returns the current dataset handle in object form."},
		},
	},
	"sslerror": {
		Title:   "SSLError",
		Summary: "Represents an SSL error and exposes its message, location, code, formatted diagnostic text, and nested SSL error details.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "SSLError{oException}",
				Description: "Wraps an exception object as an `SSLError`. In normal SSL code, use `GetLastSSLError()` instead of constructing `SSLError` yourself.",
				Parameters: []FunctionParameter{
					{Name: "oException", Type: "object", Required: true, Description: "Exception object to wrap."},
				},
			},
		},
		Properties: []ClassProperty{
			{Name: "RuntimeException", Type: "object", Access: "read-only", Description: "Low-level exception object. Prefer Description, Operation, Code, or FullDescription for typical error handling."},
			{Name: "Description", Type: "string", Access: "read-only", Description: "Primary error message text."},
			{Name: "Operation", Type: "string", Access: "read-only", Description: "Reported error location or operation name. This can be empty."},
			{Name: "GenCode", Type: "number", Access: "read-only", Description: "Numeric error code."},
			{Name: "Code", Type: "number", Access: "read-only", Description: "Alias of GenCode."},
			{Name: "FullDescription", Type: "string", Access: "read-only", Description: "Multi-line diagnostic text with abbreviated stack details and nested causes."},
			{Name: "FullDescriptionEx", Type: "string", Access: "read-only", Description: "Multi-line diagnostic text with full stack details and nested causes."},
			{Name: "NETException", Type: "object", Access: "read-only", Description: "Low-level exception object for advanced troubleshooting or interop scenarios."},
			{Name: "InnerException", Type: "SSLError", Access: "read-only", Description: "Nested SSL error when the inner cause is also an SSL runtime error. Otherwise this is empty."},
			{Name: "Message", Type: "string", Access: "read-only", Description: "Alias of Description."},
		},
	},
	"sslexpando": {
		Title:   "SSLExpando",
		Summary: "SSLExpando is a built-in object class for storing named values whose shape is decided at runtime.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "SSLExpando{}",
				Description: "Creates an empty `SSLExpando` instance.",
			},
		},
		Properties: []ClassProperty{
			{Name: "XmlType", Type: "string", Access: "read-write", Description: "XML root element name used by ToString() and Serialize()"},
		},
		Methods: []ClassMethod{
			{Name: "clone", Returns: "object", Description: "Creates a new SSLExpando with the same XmlType and current dynamic properties"},
			{Name: "GetProperty", Returns: "any", Description: "Returns the value of a named property"},
			{Name: "SetProperty", Returns: "none", Description: "Sets XmlType or a dynamic property"},
			{Name: "IsProperty", Returns: "boolean", Description: "Returns whether a property is available"},
			{Name: "GetPropList", Returns: "array", Description: "Returns the current dynamic property names"},
			{Name: "ToString", Returns: "string", Description: "Returns the object's XML representation"},
		},
	},
	"sslintdictionary": {
		Title:   "SSLIntDictionary",
		Summary: "Stores values by whole-number keys.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "SSLIntDictionary{}",
				Description: "Creates an empty dictionary.",
			},
			{
				Signature:   "SSLIntDictionary{nLength}",
				Description: "Creates an empty dictionary with an optional initial capacity hint.",
				Parameters: []FunctionParameter{
					{Name: "nLength", Type: "number", Required: false, Description: "Optional initial capacity hint. If you omit it, or pass a value that is not an integer-valued number, the dictionary uses its default starting size."},
				},
			},
		},
		Properties: []ClassProperty{
			{Name: "Count", Type: "number", Access: "read-only", Description: "Number of key-value pairs currently stored"},
			{Name: "Keys", Type: "array", Access: "read-only", Description: "Array of the current keys"},
			{Name: "Values", Type: "array", Access: "read-only", Description: "Array of the current values"},
		},
		Methods: []ClassMethod{
			{Name: "Clear", Returns: "boolean", Description: "Removes all entries and returns .T."},
			{Name: "AddValue", Returns: "boolean", Description: "Adds or replaces a value for an integer-valued numeric key"},
			{Name: "Contains", Returns: "boolean", Description: "Returns .T. when the key exists"},
			{Name: "GetValue", Returns: "any", Description: "Returns the stored value or the fallback"},
			{Name: "Remove", Returns: "boolean", Description: "Removes a key and returns whether it was removed"},
			{Name: "TryGetValue", Returns: "object", Description: "Returns an object with Exists and Value"},
		},
	},
	"sslregex": {
		Title:   "SSLRegex",
		Summary: "Matches SSL strings against a stored regular expression pattern.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "SSLRegex{sPattern}",
				Description: "| Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `sPattern` | string | yes | Regular expression pattern to store |",
				Parameters: []FunctionParameter{
					{Name: "sPattern", Type: "string", Required: true, Description: "Regular expression pattern to store"},
				},
			},
			{
				Signature:   "SSLRegex{sPattern, bCaseSensitive}",
				Description: "| Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `sPattern` | string | yes | Regular expression pattern to store | | `bCaseSensitive` | boolean | no | `.T.` for case-sensitive matching, `.F.` for case-insensitive matching. Omitting this parameter gives case-sensitive matching. |",
				Parameters: []FunctionParameter{
					{Name: "sPattern", Type: "string", Required: true, Description: "Regular expression pattern to store"},
					{Name: "bCaseSensitive", Type: "boolean", Required: false, Description: ".T. for case-sensitive matching, .F. for case-insensitive matching. Omitting this parameter gives case-sensitive matching."},
				},
			},
		},
		Properties: []ClassProperty{
			{Name: "CaseSensitive", Type: "boolean", Access: "read-only", Description: "Reports the value exposed by the class for case sensitivity"},
		},
		Methods: []ClassMethod{
			{Name: "IsMatch", Returns: "boolean", Description: "Returns whether the stored pattern matches the input string"},
		},
	},
	"sslsqlerror": {
		Title:   "SSLSQLError",
		Summary: "Represents the SQL-specific error object returned after a database failure.",
		Properties: []ClassProperty{
			{Name: "ErrorMessage", Type: "string", Access: "read-only", Description: "Combined message text from the captured database exception chain, or No Exception. when no message text was captured."},
			{Name: "SQLState", Type: "string", Access: "read-only", Description: "Provider error state or code text captured for the SQL error."},
			{Name: "ErrorStackTrace", Type: "string", Access: "read-only", Description: "Combined stack trace text from the captured exception chain, or Empty stack trace. when no stack trace text was captured."},
			{Name: "Description", Type: "string", Access: "read-only", Description: "Alias of ErrorMessage."},
			{Name: "Operation", Type: "string", Access: "read-only", Description: "Always returns SQL operation."},
			{Name: "GenCode", Type: "number", Access: "read-only", Description: "Numeric code derived from SQLState. If SQLState is a 9-character provider code, SSL tries its 5-character suffix. Returns 0 when no numeric code can be extracted."},
			{Name: "Sql", Type: "string", Access: "read-only", Description: "SQL statement associated with the captured database error, when available."},
		},
	},
	"sslstringdictionary": {
		Title:   "SSLStringDictionary",
		Summary: "Stores values by string key.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "SSLStringDictionary{}",
				Description: "Creates an empty case-insensitive dictionary.",
			},
			{
				Signature:   "SSLStringDictionary{bCaseSensitive, nLength}",
				Description: "Creates an empty dictionary with configurable case matching and an initial capacity hint.",
				Parameters: []FunctionParameter{
					{Name: "bCaseSensitive", Type: "boolean", Required: true, Description: "When true, key matching is case-sensitive. When false, matching is case-insensitive."},
					{Name: "nLength", Type: "number", Required: true, Description: "Integer-valued capacity hint for the initial dictionary size."},
				},
			},
		},
		Properties: []ClassProperty{
			{Name: "Count", Type: "number", Access: "read-only", Description: "Number of key-value pairs currently stored"},
			{Name: "Keys", Type: "array", Access: "read-only", Description: "Array of the current string keys"},
			{Name: "Values", Type: "array", Access: "read-only", Description: "Array of the current stored values"},
		},
		Methods: []ClassMethod{
			{Name: "Clear", Returns: "boolean", Description: "Removes all entries and returns .T."},
			{Name: "AddValue", Returns: "boolean", Description: "Adds or replaces a value for a string key"},
			{Name: "Contains", Returns: "boolean", Description: "Returns .T. when the key exists"},
			{Name: "GetValue", Returns: "any", Description: "Returns the stored value or the fallback"},
			{Name: "Remove", Returns: "boolean", Description: "Removes a key and returns whether it was removed"},
			{Name: "TryGetValue", Returns: "object", Description: "Returns an object with Exists and Value"},
		},
	},
	"tablesimport": {
		Title:     "TablesImport",
		Summary:   "Loads one imported table at a time from a folder structure and returns it as a CDataTable.",
		BaseClass: "EnterpriseImpExBase",
		Constructors: []ConstructorSignature{
			{
				Signature:   "TablesImport{sFolder}",
				Description: "Creates an importer for a specific root folder.",
				Parameters: []FunctionParameter{
					{Name: "sFolder", Type: "string", Required: true, Description: "Root folder that contains per-table subfolders and files."},
				},
			},
		},
		Properties: []ClassProperty{
			{Name: "NullAsBlank", Type: "boolean", Access: "read-write", Description: "Accepted property on the class, but it does not change how GetTable() imports data."},
			{Name: "IncludeORIGREC", Type: "boolean", Access: "read-write", Description: "When .F., GetTable() removes the ORIGREC column from the returned table if that column exists."},
			{Name: "ErrMsg", Type: "string", Access: "read-only", Description: "Error text set when GetTable() fails."},
		},
		Methods: []ClassMethod{
			{Name: "GetTable", Returns: "object", Description: "Loads one table from the import folder and returns it as a CDataTable, or NIL when loading fails."},
		},
	},
	"webservices": {
		Title:   "WebServices",
		Summary: "Creates client objects for outbound HTTP and SOAP integrations.",
		Constructors: []ConstructorSignature{
			{
				Signature:   "WebServices{}",
				Description: "Creates a `WebServices` factory object.",
			},
		},
		Methods: []ClassMethod{
			{Name: "CreateHttpClient", Returns: "HttpClient", Description: "Returns a new HTTP client object."},
			{Name: "CreateSoapClient", Returns: "SoapClient", Description: "Returns a new SOAP client object."},
		},
	},
}
