// Code generated by cmd/gen-inventory; DO NOT EDIT.
// Source: internal/constants/data/ssl-element-reference.json

package constants

// Generated literal inventory (3 literals).

// GeneratedLiteralDetails maps each literal slug ("true", "false", "nil") to its details.
var GeneratedLiteralDetails = map[string]LiteralDetails{
	"false": {
		Title:   "false",
		Summary: "The .F. literal represents the boolean value false in SSL. It can be written as .F. or .f. (case-insensitive). Use .F. to initialize boolean flags, to explicitly pass a false argument to a function, or to represent a negative or disabled state.",
		Syntax:  "`.F.` is case-insensitive; both `.F.` and `.f.` are valid SSL syntax.",
	},
	"nil": {
		Title:   "nil",
		Summary: "NIL is the SSL literal for an explicit absent value. It is case-insensitive, so NIL, nil, and Nil are all valid spellings.",
		Syntax:  "`NIL`",
	},
	"true": {
		Title:   "true",
		Summary: "The .T. literal represents the boolean value true in SSL and is case-insensitive.",
		Syntax:  "`.T.`",
	},
}
