// Code generated by cmd/gen-inventory; DO NOT EDIT.
// Source: internal/constants/data/ssl-element-reference.json

package constants

// Generated operator inventory and type-behavior tables (32 operators).

// GeneratedOperatorDetails maps each operator slug (e.g. "add-assign") to its symbol and behavior.
var GeneratedOperatorDetails = map[string]OperatorDetails{
	"add-assign": {
		Symbol:  "+=",
		Title:   "+= (add-assign)",
		Summary: "Updates a variable, property, or array element in place by applying + and then storing the result back into the left side.",
		Syntax:  "target += value;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "number", Behavior: "Adds the right value to the left value and stores the sum"},
			{Left: "string", Right: "string", Result: "string", Behavior: "Concatenates the right string onto the left string and stores the result"},
			{Left: "date", Right: "number", Result: "date", Behavior: "Adds the right value as days to the left date and stores the new date"},
		},
	},
	"and": {
		Symbol:  ".AND.",
		Title:   ".AND. (and)",
		Summary: "Combines two boolean expressions and returns .T. only when both are .T..",
		Syntax:  "leftBoolean .AND. rightBoolean",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "boolean", Right: "boolean", Result: "boolean", Behavior: "Returns .T. only when both operands are .T.. If the left operand is .F., the right operand is not evaluated."},
		},
	},
	"assignment": {
		Symbol:  ":=",
		Title:   ":= (assignment)",
		Summary: "Stores a value in a variable, object property, or array element and evaluates to the assigned value.",
		Syntax:  "target := value;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "variable", Right: "any", Result: "same as right", Behavior: "Stores the right-hand value in the variable"},
			{Left: "object property", Right: "any", Result: "same as right", Behavior: "Stores the right-hand value in the property"},
			{Left: "array element", Right: "any", Result: "same as right", Behavior: "Stores the right-hand value in the indexed element"},
		},
	},
	"bang": {
		Symbol:  "!",
		Title:   "! (bang)",
		Summary: "Performs boolean negation, returning the opposite boolean value.",
		Syntax:  "!booleanExpression\n!(compoundExpression)",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "n/a", Right: "boolean", Result: "boolean", Behavior: "Returns the logical negation of the operand."},
		},
	},
	"decrement": {
		Symbol:  "--",
		Title:   "-- (decrement)",
		Summary: "Decreases a number variable by one, trims trailing spaces in strings, or subtracts days from a date depending on operand type.",
		Syntax:  "--variable",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "n/a", Result: "number", Behavior: "Subtracts 1 from the number value"},
			{Left: "string", Right: "n/a", Result: "string", Behavior: "Trims trailing spaces from the string"},
			{Left: "date", Right: "n/a", Result: "date", Behavior: "Subtracts one day from the date"},
		},
	},
	"divide": {
		Symbol:  "/",
		Title:   "/ (divide)",
		Summary: "Divides the left number by the right number and returns the result as a number.",
		Syntax:  "nQuotient := nLeft / nRight;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "number", Behavior: "Returns the quotient of the left operand divided by the right operand."},
			{Left: "number", Right: "non-number", Result: "error", Behavior: "Raises a runtime operand error for /."},
			{Left: "non-number", Right: "any", Result: "error", Behavior: "Raises a runtime operator error because division is not supported for the left operand type."},
		},
	},
	"divide-assign": {
		Symbol:  "/=",
		Title:   "/= (divide-assign)",
		Summary: "Divides a numeric value by another numeric value and stores the quotient back in the left operand.",
		Syntax:  "target /= divisor;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "number", Behavior: "Divides the left operand by the right operand and stores the quotient back in the left operand."},
		},
	},
	"dollar": {
		Symbol:  "$",
		Title:   "$ (dollar)",
		Summary: "Tests whether the left string is found within the right operand as a substring.",
		Syntax:  "bResult := needle $ haystack;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "string", Right: "string", Result: "boolean", Behavior: "Returns .T. if the left string is found anywhere within the right string; otherwise .F.."},
			{Left: "string", Right: "non-string", Result: "error", Behavior: "Raises a runtime error because $ does not implicitly convert the right operand to string."},
			{Left: "non-string", Right: "any", Result: "error", Behavior: "Raises a runtime error because $ is only implemented for string left operands."},
		},
	},
	"double-star-power": {
		Symbol:  "**",
		Title:   "** (double-star-power)",
		Summary: "Raises one number to the exponent of another number.",
		Syntax:  "nResult := nBase ** nExponent;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "number", Behavior: "Raises the left operand to the power of the right operand."},
			{Left: "number", Right: "non-number", Result: "error", Behavior: "Raises a runtime error because the exponent must be numeric."},
			{Left: "non-number", Right: "any", Result: "error", Behavior: "Raises a runtime error because power is only defined for numeric bases."},
		},
	},
	"equals": {
		Symbol:  "=",
		Title:   "= (equals)",
		Summary: "Compares two values for equality, using prefix matching for strings, exact matching for numbers, booleans, and dates, and reference equality for arrays and objects.",
		Syntax:  "bEqual := vLeft = vRight;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "string", Right: "string", Result: "boolean", Behavior: "Returns .T. when the right string is empty, when both strings are equal, or when the left string starts with the right string."},
			{Left: "string", Right: "non-string", Result: "boolean", Behavior: "Returns .F.."},
			{Left: "number", Right: "number", Result: "boolean", Behavior: "Returns .T. when both numeric values are exactly equal."},
			{Left: "boolean", Right: "boolean", Result: "boolean", Behavior: "Returns .T. when both boolean values are the same."},
			{Left: "date", Right: "date", Result: "boolean", Behavior: "Returns .T. when both dates are equal."},
			{Left: "array", Right: "array", Result: "boolean", Behavior: "Returns .T. only when both operands reference the same array instance."},
			{Left: "object", Right: "object", Result: "boolean", Behavior: "Returns .T. only when both operands reference the same object instance."},
			{Left: "NIL", Right: "NIL", Result: "boolean", Behavior: "Returns .T.."},
			{Left: "NIL", Right: "non-NIL", Result: "boolean", Behavior: "Returns .F.."},
			{Left: "code block", Right: "any", Result: "error", Behavior: "Raises a runtime error."},
		},
	},
	"greater-than": {
		Symbol:  "\u003e",
		Title:   "\u003e (greater-than)",
		Summary: "Compares two values of the same supported type and returns .T. when the left operand is strictly greater than the right operand.",
		Syntax:  "vLeft \u003e vRight",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "boolean", Behavior: "Returns .T. when the left number is greater than the right number."},
			{Left: "date", Right: "date", Result: "boolean", Behavior: "Returns .T. when the left date is later than the right date."},
			{Left: "string", Right: "string", Result: "boolean", Behavior: "Returns .T. when the left string sorts after the right string in case-sensitive invariant order."},
		},
	},
	"greater-than-or-equal": {
		Symbol:  "\u003e=",
		Title:   "\u003e= (greater-than-or-equal)",
		Summary: "Compares two values of the same supported type and returns .T. when the left operand is greater than or equal to the right operand.",
		Syntax:  "vLeft \u003e= vRight",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "boolean", Behavior: "Returns .T. when the left number is greater than or equal to the right number."},
			{Left: "date", Right: "date", Result: "boolean", Behavior: "Returns .T. when the left date is later than or the same as the right date."},
			{Left: "string", Right: "string", Result: "boolean", Behavior: "Returns .T. when the left string sorts after or exactly matches the right string in case-sensitive invariant order."},
		},
	},
	"hash": {
		Symbol:  "#",
		Title:   "# (hash)",
		Summary: "Returns .T. when two values are not equal and .F. when they are equal.",
		Syntax:  "bResult := vLeft # vRight;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "boolean", Behavior: "Returns .T. when the values differ numerically."},
			{Left: "boolean", Right: "boolean", Result: "boolean", Behavior: "Returns .T. when the boolean values differ."},
			{Left: "date", Right: "date", Result: "boolean", Behavior: "Returns .T. when the dates differ."},
			{Left: "string", Right: "string", Result: "boolean", Behavior: "Returns .T. when the strings are not equal under SSL's prefix matching."},
			{Left: "string", Right: "non-string", Result: "boolean", Behavior: "Returns .T. (underlying = returns .F.)."},
			{Left: "array", Right: "array", Result: "boolean", Behavior: "Returns .T. unless both operands reference the same array instance."},
			{Left: "object", Right: "object", Result: "boolean", Behavior: "Returns .T. unless both operands reference the same object instance."},
			{Left: "NIL", Right: "NIL", Result: "boolean", Behavior: "Returns .F.."},
			{Left: "NIL", Right: "non-NIL", Result: "boolean", Behavior: "Returns .T.."},
			{Left: "number/boolean/date", Right: "incompatible", Result: "error", Behavior: "Raises a runtime invalid-operand error."},
		},
	},
	"increment": {
		Symbol:  "++",
		Title:   "++ (increment)",
		Summary: "Increases a number variable by one, modifying its value in place.",
		Syntax:  "variable++",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "n/a", Result: "number", Behavior: "Adds 1 to the variable in place."},
		},
	},
	"less-than": {
		Symbol:  "\u003c",
		Title:   "\u003c (less-than)",
		Summary: "Compares two values of the same supported type and returns .T. when the left operand is strictly less than the right operand.",
		Syntax:  "vLeft \u003c vRight",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "boolean", Behavior: "Returns .T. when the left number is less than the right number."},
			{Left: "date", Right: "date", Result: "boolean", Behavior: "Returns .T. when the left date is earlier than the right date."},
			{Left: "string", Right: "string", Result: "boolean", Behavior: "Returns .T. when the left string sorts before the right string in case-sensitive invariant order."},
		},
	},
	"less-than-or-equal": {
		Symbol:  "\u003c=",
		Title:   "\u003c= (less-than-or-equal)",
		Summary: "Compares two values of the same supported type and returns .T. when the left operand is less than or equal to the right operand.",
		Syntax:  "vLeft \u003c= vRight",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "boolean", Behavior: "Returns .T. when the left number is less than or equal to the right number."},
			{Left: "date", Right: "date", Result: "boolean", Behavior: "Returns .T. when the left date is earlier than or the same as the right date."},
			{Left: "string", Right: "string", Result: "boolean", Behavior: "Returns .T. when the left string sorts before or exactly matches the right string in case-sensitive invariant order."},
		},
	},
	"minus": {
		Symbol:  "-",
		Title:   "- (minus)",
		Summary: "Subtracts numbers, trims trailing spaces before string concatenation, or performs date arithmetic depending on operand types.",
		Syntax:  "vLeft - vRight",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "number", Behavior: "Subtracts the right numeric value from the left."},
			{Left: "string", Right: "string", Result: "string", Behavior: "Trims trailing spaces from the left operand, then concatenates the right operand."},
			{Left: "date", Right: "number", Result: "date", Behavior: "Subtracts the specified number of days from the date."},
			{Left: "date", Right: "date", Result: "number", Behavior: "Returns the difference in days between the two dates."},
		},
	},
	"modulo": {
		Symbol:  "%",
		Title:   "% (modulo)",
		Summary: "Calculates the remainder after dividing one number by another.",
		Syntax:  "nRemainder := nLeft % nRight;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "number", Behavior: "Returns the remainder of dividing the left operand by the right operand."},
			{Left: "number", Right: "non-number", Result: "error", Behavior: "Raises a runtime operand error for %."},
			{Left: "non-number", Right: "any", Result: "error", Behavior: "Raises a runtime operator error because % is not supported for the left operand type."},
		},
	},
	"modulo-assign": {
		Symbol:  "%=",
		Title:   "%= (modulo-assign)",
		Summary: "Updates a numeric variable, property, or array element in place by applying % and storing the remainder back into the left side.",
		Syntax:  "target %= divisor;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "number", Behavior: "Computes left % right, stores the remainder back into the left operand, and returns the updated value."},
		},
	},
	"multiply": {
		Symbol:  "*",
		Title:   "* (multiply)",
		Summary: "Multiplies one number by another number and returns the product.",
		Syntax:  "nProduct := nLeft * nRight;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "number", Behavior: "Returns the product of the two numeric operands."},
			{Left: "number", Right: "non-number", Result: "error", Behavior: "Raises a runtime invalid-operand error for *."},
			{Left: "non-number", Right: "any", Result: "error", Behavior: "Raises a runtime operator error because multiplication is not supported for the left operand type."},
		},
	},
	"multiply-assign": {
		Symbol:  "*=",
		Title:   "*= (multiply-assign)",
		Summary: "Multiplies a numeric value by another numeric value and stores the product back in the left operand.",
		Syntax:  "target *= value;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "number", Behavior: "Multiplies the left value by the right value and stores the product back in the left operand."},
		},
	},
	"not": {
		Symbol:  ".NOT.",
		Title:   ".NOT. (not)",
		Summary: "Performs boolean negation, returning .T. for .F. and .F. for .T..",
		Syntax:  ".NOT. booleanExpression\n.NOT. (compoundExpression)",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "n/a", Right: "boolean", Result: "boolean", Behavior: "Returns the logical negation of the operand. .NOT. .T. becomes .F., and .NOT. .F. becomes .T.."},
		},
	},
	"not-equals": {
		Symbol:  "!=",
		Title:   "!= (not-equals)",
		Summary: "Returns .T. when two values are not strictly equal under SSL equality rules.",
		Syntax:  "bDifferent := vLeft != vRight;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "string", Right: "string", Result: "boolean", Behavior: "Returns .T. when the strings are not exactly equal."},
			{Left: "string", Right: "non-string", Result: "boolean", Behavior: "Returns .T.."},
			{Left: "number", Right: "number", Result: "boolean", Behavior: "Returns .T. when the numeric values differ."},
			{Left: "boolean", Right: "boolean", Result: "boolean", Behavior: "Returns .T. when the boolean values differ."},
			{Left: "date", Right: "date", Result: "boolean", Behavior: "Returns .T. when the dates differ."},
			{Left: "array", Right: "array", Result: "boolean", Behavior: "Returns .T. unless both operands reference the same array instance."},
			{Left: "object", Right: "object", Result: "boolean", Behavior: "Returns .T. unless both operands reference the same object instance."},
			{Left: "NIL", Right: "NIL", Result: "boolean", Behavior: "Returns .F.."},
			{Left: "NIL", Right: "non-NIL", Result: "boolean", Behavior: "Returns .T.."},
			{Left: "code block", Right: "any", Result: "error", Behavior: "Raises a runtime error."},
		},
	},
	"not-equals-legacy": {
		Symbol:  "\u003c\u003e",
		Title:   "\u003c\u003e (not-equals-legacy)",
		Summary: "Returns .T. when two values are not equal under SSL's strict inequality rules.",
		Syntax:  "bDifferent := vLeft \u003c\u003e vRight;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "string", Right: "string", Result: "boolean", Behavior: "Returns .T. when the strings are not exactly equal."},
			{Left: "string", Right: "non-string", Result: "boolean", Behavior: "Returns .T.."},
			{Left: "number", Right: "number", Result: "boolean", Behavior: "Returns .T. when the numeric values differ."},
			{Left: "boolean", Right: "boolean", Result: "boolean", Behavior: "Returns .T. when the boolean values differ."},
			{Left: "date", Right: "date", Result: "boolean", Behavior: "Returns .T. when the dates differ."},
			{Left: "array", Right: "array", Result: "boolean", Behavior: "Returns .T. unless both operands reference the same array instance."},
			{Left: "object", Right: "object", Result: "boolean", Behavior: "Returns .T. unless both operands reference the same object instance."},
			{Left: "NIL", Right: "NIL", Result: "boolean", Behavior: "Returns .F.."},
			{Left: "NIL", Right: "non-NIL", Result: "boolean", Behavior: "Returns .T.."},
			{Left: "code block", Right: "any", Result: "error", Behavior: "Raises a runtime error."},
		},
	},
	"or": {
		Symbol:  ".OR.",
		Title:   ".OR. (or)",
		Summary: "Combines two boolean expressions and returns .T. when either operand is .T..",
		Syntax:  "leftBoolean .OR. rightBoolean",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "boolean", Right: "boolean", Result: "boolean", Behavior: "Returns .T. when either operand is .T.. If the left operand is .T., the right operand is not evaluated."},
		},
	},
	"plus": {
		Symbol:  "+",
		Title:   "+ (plus)",
		Summary: "Adds numbers, concatenates strings, or adds days to dates depending on operand types.",
		Syntax:  "left + right",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "number", Behavior: "Adds the two numeric values."},
			{Left: "string", Right: "string", Result: "string", Behavior: "Concatenates the two strings."},
			{Left: "date", Right: "number", Result: "date", Behavior: "Adds the numeric day offset to the date."},
		},
	},
	"power": {
		Symbol:  "^",
		Title:   "^ (power)",
		Summary: "Raises one number to the exponent of another number.",
		Syntax:  "nResult := nBase ^ nExponent;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "number", Behavior: "Raises the left operand to the power of the right operand."},
			{Left: "any other type", Right: "any", Result: "error", Behavior: "Raises an operator-not-implemented runtime error because the left operand type does not support power."},
			{Left: "number", Right: "any other type", Result: "error", Behavior: "Raises an invalid-operand runtime error because the right operand is not numeric."},
		},
	},
	"power-assign": {
		Symbol:  "^=",
		Title:   "^= (power-assign)",
		Summary: "Raises a numeric value to a numeric power and stores the result back into the left side.",
		Syntax:  "target ^= value;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "number", Behavior: "Raises the left value to the power of the right value and stores the result back in the left operand."},
		},
	},
	"shift-left": {
		Symbol:  "\u003c\u003c",
		Title:   "\u003c\u003c (shift-left)",
		Summary: "Shifts the bits of one integer number to the left by the number of positions specified by another integer number.",
		Syntax:  "nResult := nLeft \u003c\u003c nShiftCount;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "number", Behavior: "Shifts the left integer value left by the number of positions specified by the right integer value. Both operands must be numeric integers."},
		},
	},
	"shift-right": {
		Symbol:  "\u003e\u003e",
		Title:   "\u003e\u003e (shift-right)",
		Summary: "Shifts the bits of one integer number to the right by the number of positions specified by another integer number.",
		Syntax:  "nResult := nLeft \u003e\u003e nShiftCount;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "number", Behavior: "Shifts the left integer value right by the number of positions specified by the right integer value. Both operands must be numeric integers."},
		},
	},
	"strict-equals": {
		Symbol:  "==",
		Title:   "== (strict-equals)",
		Summary: "Returns .T. when two values are strictly equal under SSL equality rules.",
		Syntax:  "bEqual := vLeft == vRight;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "string", Right: "string", Result: "boolean", Behavior: "Returns .T. only when both strings are exactly equal."},
			{Left: "string", Right: "non-string", Result: "boolean", Behavior: "Returns .F.."},
			{Left: "number", Right: "number", Result: "boolean", Behavior: "Returns .T. when both numeric values are exactly equal."},
			{Left: "boolean", Right: "boolean", Result: "boolean", Behavior: "Returns .T. when both boolean values are the same."},
			{Left: "date", Right: "date", Result: "boolean", Behavior: "Returns .T. when both date values are equal."},
			{Left: "array", Right: "array", Result: "boolean", Behavior: "Returns .T. only when both operands reference the same array instance."},
			{Left: "object", Right: "object", Result: "boolean", Behavior: "Returns .T. only when both operands reference the same object instance."},
			{Left: "NIL", Right: "NIL", Result: "boolean", Behavior: "Returns .T.."},
			{Left: "NIL", Right: "non-NIL", Result: "boolean", Behavior: "Returns .F.."},
			{Left: "code block", Right: "any", Result: "error", Behavior: "Raises a runtime error."},
		},
	},
	"subtract-assign": {
		Symbol:  "-=",
		Title:   "-= (subtract-assign)",
		Summary: "Updates a variable, property, or array element in place by applying - and then storing the result back into the left side.",
		Syntax:  "target -= value;",
		TypeBehavior: []OperatorTypeBehavior{
			{Left: "number", Right: "number", Result: "number", Behavior: "Subtracts the right numeric value from the left value and stores the difference."},
			{Left: "string", Right: "string", Result: "string", Behavior: "Trims trailing spaces from the left operand, then appends the right string and stores the result."},
			{Left: "date", Right: "number", Result: "date", Behavior: "Subtracts the right value as days from the left date and stores the new date."},
			{Left: "date", Right: "date", Result: "number", Behavior: "Computes the day difference and stores that numeric result back into the left target."},
		},
	},
}

// GeneratedOperatorBySymbol indexes operator details by their literal symbol.
var GeneratedOperatorBySymbol = map[string]OperatorDetails{}

func init() {
	for _, det := range GeneratedOperatorDetails {
		if det.Symbol != "" {
			GeneratedOperatorBySymbol[det.Symbol] = det
		}
	}
}
