// Code generated by cmd/gen-inventory; DO NOT EDIT.
// Source: internal/constants/data/ssl-element-reference.json

package constants

// Inventory totals derived from the published SSL element reference.

// InventoryTotals reports element counts by category.
var InventoryTotals = struct {
	Keywords     int
	Operators    int
	Literals     int
	Types        int
	Classes      int
	SpecialForms int
	Returns      int
	Functions    int
	All          int
}{
	Keywords:     38,
	Operators:    32,
	Literals:     3,
	Types:        8,
	Classes:      29,
	SpecialForms: 8,
	Returns:      12,
	Functions:    330,
	All:          460,
}
