// Code generated by cmd/gen-inventory; DO NOT EDIT.
// Source: internal/constants/data/ssl-element-reference.json

package constants

// Generated keyword inventory and details (38 keywords).

// GeneratedKeywords lists every published SSL keyword in canonical (uppercase) form.
var GeneratedKeywords = []string{
	"BEGINCASE",
	"BEGININLINECODE",
	"CASE",
	"CATCH",
	"CLASS",
	"DECLARE",
	"DEFAULT",
	"ELSE",
	"ENDCASE",
	"ENDIF",
	"ENDINLINECODE",
	"ENDPROC",
	"ENDREGION",
	"ENDTRY",
	"ENDWHILE",
	"ERROR",
	"EXITCASE",
	"EXITFOR",
	"EXITWHILE",
	"FINALLY",
	"FOR",
	"IF",
	"INCLUDE",
	"INHERIT",
	"LABEL",
	"LOOP",
	"NEXT",
	"OTHERWISE",
	"PARAMETERS",
	"PROCEDURE",
	"PUBLIC",
	"REGION",
	"RESUME",
	"RETURN",
	"STEP",
	"TO",
	"TRY",
	"WHILE",
}

// GeneratedKeywordDetails maps each keyword (uppercase, no leading colon) to its published title, summary, and syntax block.
var GeneratedKeywordDetails = map[string]KeywordDetails{
	"BEGINCASE": {
		Title:   "BEGINCASE",
		Summary: "Starts a :BEGINCASE block for evaluating one or more boolean :CASE conditions, with an optional :OTHERWISE branch and a required :ENDCASE.",
		Syntax:  ":BEGINCASE;\n:CASE \u003ccondition\u003e;\n\t/* statements;\n\t:EXITCASE;\n:CASE \u003ccondition\u003e;\n\t/* statements;\n\t:EXITCASE;\n:OTHERWISE;\n\t/* statements;\n\t:EXITCASE;\n:ENDCASE;",
	},
	"BEGININLINECODE": {
		Title:   "BEGININLINECODE",
		Summary: "Starts a named inline SSL code block that is stored for later retrieval with GetInlineCode.",
		Syntax:  ":BEGININLINECODE BlockName;\n\t/* Inline SSL code here;\n:ENDINLINECODE;",
	},
	"CASE": {
		Title:   "CASE",
		Summary: "Executes a block of statements if a specific boolean expression evaluates to true within a CASE structure.",
		Syntax:  ":CASE expression;",
	},
	"CATCH": {
		Title:   "CATCH",
		Summary: "Handles errors raised in the immediately preceding :TRY block.",
		Syntax:  ":CATCH;",
	},
	"CLASS": {
		Title:   "CLASS",
		Summary: "Defines a class in SSL. A class file can declare fields, methods, an optional base class, and a Constructor procedure for instance initialization.",
		Syntax:  ":CLASS ClassName;",
	},
	"DECLARE": {
		Title:   "DECLARE",
		Summary: "Declares one or more variables in the current SSL scope.",
		Syntax:  ":DECLARE variable1[, variable2, ...];",
	},
	"DEFAULT": {
		Title:   "DEFAULT",
		Summary: "Assigns a fallback expression to a parameter when the caller omits that argument.",
		Syntax:  ":PARAMETERS paramName[, otherParam, ...];\n:DEFAULT paramName, defaultExpression;",
	},
	"ELSE": {
		Title:   "ELSE",
		Summary: "Directs control to an alternate set of statements when the preceding IF condition is false.",
		Syntax:  ":ELSE;",
	},
	"ENDCASE": {
		Title:   "ENDCASE",
		Summary: "Closes a :BEGINCASE block after its :CASE branches and optional :OTHERWISE branch.",
		Syntax:  ":ENDCASE;",
	},
	"ENDIF": {
		Title:   "ENDIF",
		Summary: "Terminates an :IF block, with or without an :ELSE branch.",
		Syntax:  ":ENDIF;",
	},
	"ENDINLINECODE": {
		Title:   "ENDINLINECODE",
		Summary: "Ends a named inline SSL code block opened by :BEGININLINECODE.",
		Syntax:  ":ENDINLINECODE;",
	},
	"ENDPROC": {
		Title:   "ENDPROC",
		Summary: "Terminates a procedure block and signals the end of its executable statements.",
		Syntax:  ":ENDPROC;",
	},
	"ENDREGION": {
		Title:   "ENDREGION",
		Summary: "Keyword that marks the end of a :REGION block; it has no standalone runtime behavior.",
		Syntax:  ":ENDREGION;",
	},
	"ENDTRY": {
		Title:   "ENDTRY",
		Summary: "Closes a structured :TRY block after its :CATCH and/or :FINALLY sections.",
		Syntax:  ":ENDTRY;",
	},
	"ENDWHILE": {
		Title:   "ENDWHILE",
		Summary: "Closes a :WHILE loop block.",
		Syntax:  ":ENDWHILE;",
	},
	"ERROR": {
		Title:   "ERROR",
		Summary: "Defines a legacy error handler for the statements that follow it in the current procedure or method.",
		Syntax:  ":ERROR;",
	},
	"EXITCASE": {
		Title:   "EXITCASE",
		Summary: "Ends the current :CASE or :OTHERWISE branch and continues after :ENDCASE.",
		Syntax:  ":EXITCASE;",
	},
	"EXITFOR": {
		Title:   "EXITFOR",
		Summary: "Terminates the innermost active :FOR loop immediately and continues with the statement after the matching :NEXT.",
		Syntax:  ":EXITFOR;",
	},
	"EXITWHILE": {
		Title:   "EXITWHILE",
		Summary: "Terminates the innermost active :WHILE loop and continues with the statement after the matching :ENDWHILE.",
		Syntax:  ":EXITWHILE;",
	},
	"FINALLY": {
		Title:   "FINALLY",
		Summary: "Starts the cleanup section of a :TRY block and always runs after the protected work completes.",
		Syntax:  ":FINALLY;",
	},
	"FOR": {
		Title:   "FOR",
		Summary: "Executes a counted loop by assigning a numeric variable, checking it against a numeric limit, and updating it after each iteration.",
		Syntax:  ":FOR nIndex := nStart :TO nEnd [:STEP nStep];",
	},
	"IF": {
		Title:   "IF",
		Summary: "Executes a block of statements only when a condition evaluates to true.",
		Syntax:  ":IF condition;\n    /* Statements to run when condition is true;\n:ELSE;\n    /* Optional statements to run when condition is false;\n:ENDIF;",
	},
	"INCLUDE": {
		Title:   "INCLUDE",
		Summary: "Inserts another SSL script's source into the current file so its statements compile as if they were written inline.",
		Syntax:  ":INCLUDE scriptName;",
	},
	"INHERIT": {
		Title:   "INHERIT",
		Summary: "Specifies the parent class for an SSL class.",
		Syntax:  ":INHERIT ClassName;",
	},
	"LABEL": {
		Title:   "LABEL",
		Summary: "Marks a named location in a procedure or script for control flow redirection.",
		Syntax:  ":LABEL labelText;\n:LABEL labelPart moreParts;\n:LABELlabelText;",
	},
	"LOOP": {
		Title:   "LOOP",
		Summary: "Skips the rest of the current :WHILE or :FOR iteration and continues with the next iteration of the innermost active loop.",
		Syntax:  ":LOOP;",
	},
	"NEXT": {
		Title:   "NEXT",
		Summary: "Closes a :FOR loop and returns control to the loop's increment-and-test step.",
		Syntax:  ":NEXT;",
	},
	"OTHERWISE": {
		Title:   "OTHERWISE",
		Summary: "Executes the default branch of a :BEGINCASE block when no earlier :CASE branch runs.",
		Syntax:  ":OTHERWISE;",
	},
	"PARAMETERS": {
		Title:   "PARAMETERS",
		Summary: "Declares named input parameters for a script, procedure, method, or constructor.",
		Syntax:  ":PARAMETERS param1[, param2, ...];",
	},
	"PROCEDURE": {
		Title:   "PROCEDURE",
		Summary: "Declares a named routine body that can contain executable SSL statements and end with :ENDPROC ;.",
		Syntax:  ":PROCEDURE ProcedureName;",
	},
	"PUBLIC": {
		Title:   "PUBLIC",
		Summary: "Declares public variables shared down the call stack — visible to the declaring scope and every scope it calls.",
		Syntax:  ":PUBLIC variable1[, variable2, ...];",
	},
	"REGION": {
		Title:   "REGION",
		Summary: "Starts a named region block whose body is stored as text for later retrieval with GetRegion().",
		Syntax:  ":REGION RegionName;\nregion body text\n:ENDREGION;",
	},
	"RESUME": {
		Title:   "RESUME",
		Summary: "Continues execution after a legacy :ERROR handler, starting with the statement after the one that failed.",
		Syntax:  ":RESUME;",
	},
	"RETURN": {
		Title:   "RETURN",
		Summary: "Ends the current script, procedure, or method immediately and can optionally return a value.",
		Syntax:  ":RETURN;\n:RETURN expression;",
	},
	"STEP": {
		Title:   "STEP",
		Summary: "Sets the increment or decrement used by a :FOR loop between iterations.",
		Syntax:  ":FOR nIndex := nStart :TO nEnd [:STEP nStep];",
	},
	"TO": {
		Title:   "TO",
		Summary: "Sets the inclusive loop limit used by a :FOR loop.",
		Syntax:  ":FOR nIndex := nStart :TO nEnd [:STEP nStep];",
	},
	"TRY": {
		Title:   "TRY",
		Summary: "Starts a protected block that can transfer control to :CATCH, :FINALLY, or both when errors occur.",
		Syntax:  ":TRY;\n    try_statements;\n:CATCH;\n    catch_statements;\n:ENDTRY;",
	},
	"WHILE": {
		Title:   "WHILE",
		Summary: "Repeats a block of statements as long as a supplied condition evaluates to true.",
		Syntax:  ":WHILE condition;\n    /* loop body;\n:ENDWHILE;",
	},
}
