// Code generated by cmd/gen-inventory; DO NOT EDIT.
// Source: internal/constants/data/ssl-element-reference.json

package constants

// Generated special-form inventory (8 special forms).

// GeneratedSpecialFormDetails maps each special-form slug to its details.
var GeneratedSpecialFormDetails = map[string]SpecialFormDetails{
	"access-modifiers": {
		Title:   "Access Modifiers",
		Summary: "SSL supports two comment-based access modifiers that control procedure visibility. Place one on the line immediately before a :PROCEDURE declaration.",
		Syntax:  "/*@private;\n:PROCEDURE ProcedureName;\n\n/*@protected;\n:PROCEDURE ProcedureName;",
	},
	"base": {
		Title:   "Base:",
		Summary: "Provides explicit access to members on a class's immediate parent type from within a class method.",
		Syntax:  "Base:FieldName;\nBase:MethodName(args);\nBase:Constructor(args);",
	},
	"code-block": {
		Title:   "Code Block",
		Summary: "Defines an anonymous code block with bound variables and a single expression body. A code block can be created at the top level, passed as a function argument, or assigned to a variable for later execution.",
		Syntax:  "{|param1| expression}\n{|param1, param2| expression}",
	},
	"code-organization": {
		Title:   "Code Organization",
		Summary: "Comment regions group related procedures or code sections in long files. They are purely organizational - they have no effect on compilation or execution, but development tools use them for code folding and navigation.",
		Syntax:  "/* region Region Name;\n\n/* region content;\n\n/* endregion;",
	},
	"constructor": {
		Title:   "Constructor",
		Summary: "Runs one-time class initialization code when a user-defined class instance is created.",
		Syntax:  ":CLASS MyClass;\n\n:PROCEDURE Constructor;\n    /* Initialization code;\n:ENDPROC;",
	},
	"me": {
		Title:   "Me:",
		Summary: "Provides a reference to the current class instance inside :CLASS methods.",
		Syntax:  "Me;\nMe:FieldName;\nMe:MethodName(args);",
	},
	"request": {
		Title:   "Request",
		Summary: "An ambient identifier in endpoint scripts that holds the incoming HTTP request.",
		Syntax:  "Request;\nRequest:PropertyName;\nRequest:CollectionName:Key;\nRequest:MethodName(args);",
	},
	"response": {
		Title:   "Response",
		Summary: "An ambient identifier in endpoint scripts that holds the outgoing HTTP response.",
		Syntax:  "Response:PropertyName := value;\nResponse:MethodName(args);",
	},
}
