// Code generated by cmd/gen-inventory; DO NOT EDIT.
// Source: internal/constants/data/ssl-element-reference.json

package constants

// Generated returns-object inventory: properties and methods of objects returned by built-in class methods (12 objects).

// GeneratedReturnsObjectNames is the canonical PascalCase list of returns-category objects.
var GeneratedReturnsObjectNames = []string{
	"HttpClient",
	"HttpException",
	"HttpRequest",
	"HttpResponse",
	"SoapClient",
	"SoapParameters",
	"SoapResponse",
	"SSLNameValueContainer",
	"SSLRequest",
	"SSLResponse",
	"SSLWsRequest",
	"SSLWsResponse",
}

// GeneratedReturnsObjectDetails maps each returns-object name (lowercase) to its properties and methods.
var GeneratedReturnsObjectDetails = map[string]ReturnsObjectDetails{
	"httpclient": {
		Title:   "HttpClient",
		Summary: "Entry point for outbound HTTP requests — builds requests, fetches responses, and retrieves text, XML, or files.",
		Methods: []ClassMethod{
			{Name: "CreateHttpRequest", Returns: "HttpRequest", Description: "Creates a configurable request for the given URL."},
			{Name: "GetResponse", Returns: "HttpResponse", Description: "Sends a request and returns the response."},
			{Name: "GetLastServerException", Returns: "HttpException", Description: "Returns the most recent failure, or NIL if the last call succeeded."},
			{Name: "GetText", Returns: "string", Description: "Sends a request and returns the body as text."},
			{Name: "GetXmlDom", Returns: "object", Description: "Sends a request and returns the body as an XML DOM object."},
			{Name: "SaveFile", Returns: "string", Description: "Sends a request and writes the body to a file."},
		},
	},
	"httpexception": {
		Title:   "HttpException",
		Summary: "Details on a failed HTTP request — status, message, and the server's response body.",
		Properties: []ClassProperty{
			{Name: "StatusCode", Type: "number", Access: "read-only", Description: "A numeric code identifying the failure mode (e.g., timeout, name resolution failure, protocol error)."},
			{Name: "Status", Type: "string", Access: "read-only", Description: "A short text label for the failure mode (e.g., Timeout, ConnectFailure, ProtocolError)."},
			{Name: "Message", Type: "string", Access: "read-only", Description: "A short, human-readable description of the failure."},
			{Name: "MessageDetails", Type: "string", Access: "read-only", Description: "The server's response body when one was returned. Falls back to a \"Server is unable to provide more information\" message followed by Message when no body is available."},
		},
	},
	"httprequest": {
		Title:   "HttpRequest",
		Summary: "A configurable outbound HTTP request — method, headers, content type, body, and timeout.",
		Properties: []ClassProperty{
			{Name: "UserAgent", Type: "string", Access: "read-write", Description: "The User-Agent header value."},
			{Name: "Timeout", Type: "number", Access: "read-write", Description: "Maximum wait, in milliseconds, for the response."},
			{Name: "ContentType", Type: "string", Access: "read-write", Description: "The Content-Type header for the request body (e.g., application/json)."},
			{Name: "ContentLength", Type: "number", Access: "read-write", Description: "Byte length of the request body. Set automatically by SetContent; assign explicitly only when streaming bodies you build by hand."},
			{Name: "Method", Type: "string", Access: "read-write", Description: "HTTP method (GET, POST, PUT, DELETE, etc.). Defaults to GET."},
			{Name: "Accept", Type: "string", Access: "read-write", Description: "The Accept header value."},
		},
		Methods: []ClassMethod{
			{Name: "AddHeader", Returns: "none", Description: "Adds a custom request header."},
			{Name: "SetContent", Returns: "none", Description: "Sets the request body. Multiple forms accept text, binary, or multipart content."},
			{Name: "SetContentFromFile", Returns: "none", Description: "Sets the request body to the contents of a file."},
			{Name: "CreateHttpForm", Returns: "object", Description: "Returns a multipart form object you can populate and pass to SetContent."},
		},
	},
	"httpresponse": {
		Title:   "HttpResponse",
		Summary: "An HTTP response — content metadata, headers, and the body as text, XML, or a saved file.",
		Properties: []ClassProperty{
			{Name: "ContentLength", Type: "number", Access: "read-only", Description: "Length of the response body in bytes, as reported by the server."},
			{Name: "ContentEncoding", Type: "string", Access: "read-only", Description: "The Content-Encoding header value (e.g., gzip)."},
			{Name: "ContentType", Type: "string", Access: "read-only", Description: "The Content-Type header value."},
			{Name: "HeaderNames", Type: "array", Access: "read-only", Description: "All response header names, as an array of strings. Use with GetHeader to read individual values."},
		},
		Methods: []ClassMethod{
			{Name: "GetHeader", Returns: "string", Description: "Returns the value of a named response header."},
			{Name: "GetValueAsString", Returns: "string", Description: "Returns the response body as text."},
			{Name: "GetValueAsXmlDom", Returns: "object", Description: "Returns the response body parsed as an XML DOM object."},
			{Name: "SaveValueToFile", Returns: "string", Description: "Writes the response body to a file and returns the path."},
		},
	},
	"soapclient": {
		Title:   "SoapClient",
		Summary: "Calls SOAP web services — configures the endpoint from a WSDL, supplies credentials, invokes methods.",
		Properties: []ClassProperty{
			{Name: "Error", Type: "string", Access: "read-write", Description: "The reason the most recent configuration step failed. Empty string when the last step succeeded."},
			{Name: "TimeOut", Type: "number", Access: "read-write", Description: "Maximum wait, in milliseconds, for a CallWebService invocation. Values \u003c= 0 disable the timeout."},
			{Name: "Parameters", Type: "SoapParameters", Access: "read-write", Description: "The parameter list passed to the next CallWebService invocation. Replace it with another instance, or call its add methods directly."},
			{Name: "AcceptCookies", Type: "boolean", Access: "read-write", Description: "When .T. (the default), the client retains cookies set by the service across calls."},
			{Name: "UseDefaultCredentials", Type: "boolean", Access: "read-write", Description: "When .T., calls authenticate with the calling process's default credentials. Falls back to GlobalUseDefaultCredentials when not set explicitly on the client."},
			{Name: "GlobalUseDefaultCredentials", Type: "boolean", Access: "read-write", Description: "Class-wide default for UseDefaultCredentials. Affects every SoapClient that has not set the property locally."},
			{Name: "WsAssembly", Type: "object", Access: "read-only", Description: "Advanced — a handle to the generated proxy types for the configured WSDL. Used internally by Parameters:CreateCustomType and GetWSType; rarely needed directly."},
		},
		Methods: []ClassMethod{
			{Name: "UseWebService", Returns: "boolean", Description: "Configures the client from a WSDL location, with no credentials."},
			{Name: "UseWebServiceWithCredentials", Returns: "boolean", Description: "Configures the client from a WSDL location with explicit user/password."},
			{Name: "UseProxy", Returns: "boolean", Description: "Advanced — configures the client from a pre-built proxy file."},
			{Name: "CallWebService", Returns: "SoapResponse", Description: "Invokes a SOAP method on the configured service."},
			{Name: "GetWSType", Returns: "object", Description: "Advanced — returns a handle to a named proxy type."},
		},
	},
	"soapparameters": {
		Title:   "SoapParameters",
		Summary: "The parameter list passed to the next SOAP method invocation — add scalar, XML-typed, binary, or by-reference parameters.",
		Methods: []ClassMethod{
			{Name: "Add", Returns: "none", Description: "Adds one parameter from an XML representation."},
			{Name: "AddAll", Returns: "none", Description: "Adds several parameters from an XML array."},
			{Name: "AddByRef", Returns: "none", Description: "Like Add, and flags the parameter as by-reference."},
			{Name: "AddBinary", Returns: "none", Description: "Adds a binary parameter sourced from a file."},
			{Name: "AddBinaryByRef", Returns: "none", Description: "Like AddBinary, and flags the parameter as by-reference."},
			{Name: "AddParameter", Returns: "none", Description: "Adds a parameter from an SSL value directly."},
			{Name: "AddParameterByRef", Returns: "none", Description: "Like AddParameter, and flags the parameter as by-reference."},
			{Name: "AddParameter2", Returns: "none", Description: "Adds a parameter from an SSL value with an explicit type name."},
			{Name: "AddParameters", Returns: "none", Description: "Appends every parameter from another SoapParameters (preserving by-reference flags)."},
			{Name: "CreateCustomType", Returns: "object", Description: "Returns a new instance of a custom DTO defined in the WSDL."},
			{Name: "Clear", Returns: "none", Description: "Removes all parameters and by-reference flags."},
		},
	},
	"soapresponse": {
		Title:   "SoapResponse",
		Summary: "The result of a SOAP call — read scalar values, navigate object fields and arrays, save binary results, or get the result as XML.",
		Properties: []ClassProperty{
			{Name: "ValueAsStringDate", Type: "string", Access: "read-only", Description: "The wrapped value formatted as YYYY-M-D when the value is a date. Empty string otherwise."},
			{Name: "ValueAsStringTime", Type: "string", Access: "read-only", Description: "The wrapped value formatted as HH:MM:SS (zero-padded) when the value is a date/time. Empty string otherwise."},
			{Name: "Xml", Type: "string", Access: "read-only", Description: "The wrapped value serialized to XML. Empty string when serialization fails; in that case, the parent SoapClient's Error property is set."},
			{Name: "XmlByRef", Type: "string", Access: "read-only", Description: "The by-reference parameter values from the call serialized to XML. Empty string when there are none or serialization fails."},
		},
		Methods: []ClassMethod{
			{Name: "Value", Returns: "object", Description: "Returns the wrapped value as-is."},
			{Name: "UnWrap", Returns: "object", Description: "Returns the wrapped value, expanding arrays of complex types into arrays of SoapResponse."},
			{Name: "GetObjectField", Returns: "SoapResponse", Description: "Returns a named field of a complex result."},
			{Name: "GetArrayItem", Returns: "SoapResponse", Description: "Returns an element of an array result."},
			{Name: "GetArrayLength", Returns: "number", Description: "Returns the length of an array result, or -1 when the result is not an array."},
			{Name: "SaveToFile", Returns: "string", Description: "Writes a binary result to a file."},
			{Name: "GetTypeInfo", Returns: "string", Description: "Returns a name for the wrapped value's type."},
			{Name: "GetObjectFieldList", Returns: "string", Description: "Returns the names and types of all fields on a complex result, as XML."},
		},
	},
	"sslnamevaluecontainer": {
		Title:   "SSLNameValueContainer",
		Summary: "A name/value bag — read or list values from a request's headers, query string, cookies, forms, server variables, or client certificate fields.",
		Properties: []ClassProperty{
			{Name: "AllKeys", Type: "array", Access: "read-only", Description: "Every key in the collection, as an array of strings. Returns an empty array when the collection has no entries."},
		},
	},
	"sslrequest": {
		Title:   "SSLRequest",
		Summary: "The incoming HTTP request inside an endpoint script — method, URL, headers, query string, cookies, forms, body, and uploaded files.",
		Methods: []ClassMethod{
			{Name: "SaveInputStream", Returns: "string", Description: "Saves the request body to a file and returns the path."},
		},
	},
	"sslresponse": {
		Title:   "SSLResponse",
		Summary: "The outgoing HTTP response inside an endpoint script — write content, set status, redirect, add headers and cookies.",
		Properties: []ClassProperty{
			{Name: "ContentType", Type: "string", Access: "read-write", Description: "The response Content-Type header (e.g., application/json, text/html)."},
			{Name: "StatusCode", Type: "number", Access: "read-write", Description: "The HTTP status code to send (200, 400, 404, 500, etc.)."},
			{Name: "Tag", Type: "string", Access: "read-write", Description: "A free-form tag used to associate the response with a cache invalidation key."},
			{Name: "CacheRetention", Type: "number", Access: "read-write", Description: "How long the response may be cached, in seconds."},
			{Name: "InvalidateCache", Type: "boolean", Access: "read-write", Description: "When .T., signals that any cached entry for this response should be discarded."},
			{Name: "InvalidateCacheByTag", Type: "string", Access: "read-write", Description: "A tag value; cached entries marked with this tag are discarded."},
		},
		Methods: []ClassMethod{
			{Name: "Write", Returns: "none", Description: "Appends text to the response body."},
			{Name: "WriteFile", Returns: "none", Description: "Appends the contents of a file to the response body."},
			{Name: "Redirect", Returns: "none", Description: "Sends a redirect to the given URL."},
			{Name: "AddHeader", Returns: "none", Description: "Adds a custom response header."},
			{Name: "AddCookie", Returns: "none", Description: "Adds a cookie to the response."},
			{Name: "SetCookie", Returns: "none", Description: "Sets (or replaces) a cookie on the response."},
			{Name: "Flush", Returns: "none", Description: "Sends any buffered content immediately."},
			{Name: "End", Returns: "none", Description: "Ends the response — no further content is sent after this call."},
			{Name: "DisablePageCaching", Returns: "none", Description: "Suppresses caching for this response."},
			{Name: "Send401", Returns: "none", Description: "Sends a 401 Unauthorized status with the appropriate authentication challenge."},
		},
	},
	"sslwsrequest": {
		Title:   "SSLWsRequest",
		Summary: "The web-service variant of the request object — adds Parameters to everything an SSLRequest exposes.",
		Properties: []ClassProperty{
			{Name: "Parameters", Type: "array", Access: "read-only", Description: "The positional parameters of the call, in the order the caller supplied them. Empty array when there are no parameters."},
		},
	},
	"sslwsresponse": {
		Title:   "SSLWsResponse",
		Summary: "The web-service variant of the response object — adds Value (the structured return) to everything an SSLResponse exposes.",
		Properties: []ClassProperty{
			{Name: "Value", Type: "any", Access: "read-write", Description: "The script's return value to the web-service caller. The runtime serializes the assigned value into the appropriate response format."},
		},
	},
}
